### ISSUE TITLE
Question, is it healthy to self-play using one net for longer time?

### ISSUE THREAD

**Issue by Marcin1960** [leela-zero/leela-zero#1164] opened 2018-04-08 06:56 UTC
Would it be good to promote some hand picked 50% plus net once a while?

I would pick a net created with some time/SWA difference.

**Comment by Friday9i** [comment] 2018-04-08 07:42
No data, but I share your feeling: a pool of network (all the one above 50%?) may be much more healthy to bring some diversity and avoid specialisation / overfitting. Also, playing some games with more plies good be useful: I noticed you see other shapes when playing 30K to 500K visits. Maybe 1% of the games played at 10x more visits could help with better play, diversity and in the end give a boost to learning?
Anyway, I know, no hard data to support these ideas.

**Comment by Marcin1960** [comment] 2018-04-08 07:44
I do not mean always promote above 50%. But hand picked decent net every 1/3 of the window.

**Comment by Friday9i** [comment] 2018-04-08 07:51
"I do not mean always promote above 50%": neither me, a simple approach would rather be to generate selfplay games from all networks above 50% (ie the "current one" + the others having achieved > 50%) and keep the same SPRT test. I guess it should be easy to implement (as well a playing some games with 10x more visits).

**Comment by Friday9i** [comment] 2018-04-08 09:27
If as currently we have one official net (LZ116) and 10 nets between 50% and 55% (!), making selfplay games with these 11 nets would give for sure more diversity. Moreover, making a few % of games with much more visits (10x more?) would add more diversity and better games.
That's a "very low cost" approach (almost no development to do, almost no impact on number of games generated) and it may help: why not try?

**Comment by PhilipFRipper** [comment] 2018-04-08 09:49
"No data, but"  Then test it yourself to produce data.  Blind speculation doesn't help.

**Comment by Friday9i** [comment] 2018-04-08 11:46
To test it, I need both a lot of computer power and skills and experience to train networks, and as you can guess I don't get them.
But the idea being easy to test for the dev team, I'm suggesting to test it.
Either the dev team tries it and I'd be happy to see the results, or it doesn't and so be it...

**Comment by Marcin1960** [comment] 2018-04-08 14:06
Is the slowdown in 10x128 progress related to the introduction of 20x256 processing?

**Comment by jkiliani** [comment] 2018-04-08 18:29
I'm hoping the 192x15 net @gcp has been training up is close to being competitive...

**Comment by jkiliani** [comment] 2018-04-09 06:17
Leela chess currently has problems in the variety of its match games due to the lack of useful symmetries, their only variability stem from Dirichlet noise. As a result, current matches are likely biased since they only represent a small part of valid opening lines.

I recently coded a fix for this with https://github.com/glinscott/leela-chess/pull/267, which looks like it can provide much more variations with similar strength.

Regardless, Leela Chess results are certainly encouraging for the always-promote concept. It appears the faster feedback cycle does actually help considerably.

**Comment by gcp** [comment] 2018-04-09 12:24
More variety certainly helps, not regressing the quality of the games probably helps too. Note that the current parameters are set to make it 95% sure we don't introduce regressions. Lowering the pass rate to 50% or less removes this guarantee (which could for example be reinforced by playing more match games, etc).

I think the faster cycle (and ability to use less playouts) are probably good especially for very large nets for reasons already outlined several times.

**Comment by Eddh** [comment] 2018-04-09 12:56
If I understand right the gating is more about being 95% sure that the promoted net is 35 elo stronger, not 95% sure that is not worse, so it's stricter than you make it sound. But anyway since dozens of net are tested it's like rolling dice dozen of time in a row, you're bound to get lucky sometimes, so this 95% guarantee doesn't hold in practice.

**Comment by Alderi-Tokori** [comment] 2018-04-09 13:01
@Eddh The current gating makes us sure that there's a 95% probability that the net is stronger than the previous one (55% winrate at 400 games is 2 sdevs away from 50%, meaning if a net has 55%+ winrate at 400 games, it has 95%+ chance of actually being stronger).

**Comment by Eddh** [comment] 2018-04-09 13:08
@Alderi-Tokori dozens of nets are tested, so even if they are all at same strength as previous best one, you can still get one that will pass the gating, by luck. That means we don't have this 95% guarantee for promoted nets.

If you roll a dice, you have 1/6 chance of getting a 6, but if you roll the dice hundreds of time, you will very probably get at least one 6.

**Comment by Alderi-Tokori** [comment] 2018-04-09 14:13
@Eddh 

> dozens of nets are tested, so even if they are all at same strength as previous best one, you can still get one that will pass the gating, by luck. That means we don't have this 95% guarantee for promoted nets.

It exactly mean we have that 95% guarantee, but note 95% is not 100%, so some net passing doesn't invalidate this model.

To make a parallel with your analogy, sure, for some coins, there will be more than 55% head, but I can tell you mathematically that exactly 5% of your coins (if you launched an infinite number of coins, that is) will have 55%+ head or tail. I mean that's just how probabilities work. In the same way, there is one coin in every 2^400 that has 400 head or tail, but it doesn't mean at all that the chance to have a head or a tail is any different than 50%.

The fact that these """unlikely""" scenarios happen doesn't invalidate the guarantee that "95% of net that will be promoted will indeed be stronger".

Furthermore, if a net passes and was indeed actually a bit weaker, then the next time another net that was a bit stronger might pass too, so it sorts itself out in the end.

**Comment by Eddh** [comment] 2018-04-09 14:44
>but it doesn't mean at all that the chance to have a head or a tail is any different than 50%.
That is the point. You can have a 99% winrate network every 2^400 networks, that doesn't mean you are 95% sure that this network is stronger.

I agree that it is not much of a problem because the AZ method uses always promote anyway and a network that won more games has more chances to be good than another, but the point is that you have absolutely no guarantee that 95% of nets that are promoted are 35 elo stronger.

**Comment by gcp** [comment] 2018-04-09 14:51
>If I understand right the gating is more about being 95% sure that the promoted net is 35 elo stronger, not 95% sure that is not worse, so it's stricter than you make it sound

It's more complicated but I don't want to awake that discussion again :package: 

Anyway, obviously with 100's of tests some will pass incorrectly, but I was pointing out that the 55% choice was not "random" and that if you say it must be 50%, you must be able to explain why this magic value is better than my magic value (or none at all).

**Comment by Eddh** [comment] 2018-04-09 15:33
No you can't say 95% chance to be stronger than the previous one. Given the coin flip analogy, imagine you have magical coins that ends on head 40% of the time. If you use billions of these coins or something, you would have some of them that got lucky and ended on head 90% of the time. That doesn't mean these coins are different and have a >50% chance of ending on head, they just got lucky.

It's the same as a researcher doing an experiment, he finds it is not statistically significant, so he does it again, and again, and again, until he gets a statistically significant result.

**Comment by Alderi-Tokori** [comment] 2018-04-09 15:53
@Eddh I think you're confusing yourself with your analogy because it adds a useless layer of complexity: If we had 1 billion coins (strictly identical) and launched each of them 400 times, it'd be exactly the same as launching one 400 billion times. Here, in a promotion match (or a coin flip), we're actually calculating a binomial law, which is a gaussian curve for which the mean is equal to the actual "success" probability and the standard deviation is derived from the number of flips/games and the success probabilities. The more coin flips you do, the more "certain" you can be of your result because the standard deviation becomes smaller and smaller.

In your (well, our, we both used it) coin flip analogy, sometimes you have 400 heads in a row, which is extremely unlikely, but drowned in the billions of other results, it doesn't affect the end probabilities. When I said "it doesn't mean at all that the chance to have a head or a tail is any different than 50%", what I meant is you can't choose what results to keep after the launches: the more you launch coins, the more chance you have of seeing a long head streak, but you can't just keep this streak, you have to keep all results.

The thing with probabilistic maths is that unless you launch an infinity of coins, there will always be a small chance of getting only heads, even with 400 billion launches, it can happen. So we can always only say "we have X% chance to really be between Y and Z". And that's what we do here: after 400 games, we say we have 95% chance of being in the displayed winrate +-5% range.

If this extremely unlikely (I'm taking the extreme case) event of "we get only wins but the net's real winrate is 45%" happens, then we'd have really bad luck, but it would still be mathematically sound to say we are 95%+ sure that the net is stronger than the previous one.

**Comment by Eddh** [comment] 2018-04-09 16:13
No it's absolutely not true to say that
 > after 400 games, we say we have 95% chance of being in the displayed winrate +-5% range

It would be true if you do that in isolation, it is not true if you do this 400 games test many times. Because no matter what, you will end up, after you have done this 400 games test enough times, with a >55% winrate in one of the tests. We could use the same net over and over again, testing it against itself, and we would end up regularly having >55% winrate. We could use an older net that we know to be weaker, and if we do the 400 games test many times, it will end up with >55% winrate at some point.

This is actually a huge problems with science currently. People don't publish their inconclusive results, only "conclusive" ones. And if there are 20 unconclusive results for 1 conclusive one, we would only hear about the conclusive one, claiming their result has 95% chances to be true...

**Comment by dfannius** [comment] 2018-04-09 16:41
What @Eddh keeps saying seems so self-evidently true to me that it is worrisome to me that people are arguing against it, making me feel like I'm missing something.

If we run the current promotion system with networks that are all identical except for their ID, every once in a while one will pass the 55% threshold and promote, and our Elo graph will keep going slowly up, despite the fact that by design every network has a 0% chance of actually being better than the current champion.

**Comment by Eddh** [comment] 2018-04-09 16:48
Maybe another explanation would be this : the 95% chance mathematically assumes 400 games, but in truth, dozens of set of 400 games are played, and all the gating does is pick a set of 400 games which coincidentally has >55% winrate

**Comment by gcp** [comment] 2018-04-09 17:42
Yeah this is the typical problem with multiple testing. There's no "real" solution for this that doesn't increase missing the chance of a good network or playing a ton more test games.

**Comment by Alderi-Tokori** [comment] 2018-04-09 20:46
@dfannius Yeah, we chatted on discord and Eddh managed to explain to me what was wrong in my reasoning.

**Comment by sethtroisi** [comment] 2019-02-14 06:45
closing older issues, no discussion for >6 months

**Closed by sethtroisi** 2019-02-14 06:45 UTC
