### ISSUE TITLE
Compiling error on Ubuntu 14.04

### ISSUE THREAD

**Issue by hjianhao** [leela-zero/leela-zero#335] opened 2017-12-10 12:18 UTC
When using make to compile the master branch of leela-zero, I got the following errors:

Network.cpp: In static member function ‘static void Network::initialize()’:
Network.cpp:241:31: error: ‘openblas_set_num_threads’ was not declared in this scope
     openblas_set_num_threads(1);
                               ^
Network.cpp:242:55: error: ‘openblas_get_corename’ was not declared in this scope
     myprintf("BLAS Core: %s\n", openblas_get_corename());

I had done the previous steps with no errors:
```
# Test for OpenCL support & compatibility
sudo apt install clinfo && clinfo

# Clone github repo
git clone https://github.com/gcp/leela-zero
cd leela-zero/src
sudo apt install libboost-all-dev libopenblas-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev
```

**Comment by isty2e** [comment] 2017-12-10 12:27
This is weird, with openblas installed this is not suppose to happen. Could you try compiling in a new shell?

**Comment by marcocalignano** [comment] 2017-12-10 12:40
@hjianhao try the following

```
cd leela-zero/
mkdir build
cd build
cmake ..
make 

```

**Comment by hjianhao** [comment] 2017-12-10 13:13
I had solved manually with following steps.

first I found there is no /usr/include/openblas directory, even I had installed  libopenblas-dev

so I clone OpenBLAS from github and compiled it. 
git clone git://github.com/xianyi/OpenBLAS
cd OpenBLAS
sudo apt-get install gfortran
sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so
sudo make FC=gfortran
sudo make install

then I modified the Makefile in src, then I can compile leela-zero.

from 
ifeq ($(THE_OS),Linux)
# for Linux with OpenBLAS
        CXXFLAGS += -I/usr/include/openblas
        DYNAMIC_LIBS += -lopenblas
        DYNAMIC_LIBS += -lOpenCL
endif

to 

ifeq ($(THE_OS),Linux)
# for Linux with OpenBLAS
        CXXFLAGS += -I/opt/OpenBLAS/include
        LDFLAGS  += -L/opt/OpenBLAS/lib
        DYNAMIC_LIBS += -lopenblas
        DYNAMIC_LIBS += -lOpenCL
endif

**Comment by marcocalignano** [comment] 2017-12-10 13:19
@hjianhao can you still run the cmake and post the output please

**Comment by hjianhao** [comment] 2017-12-10 13:25
I had done the following steps:

```
cd leela-zero/
mkdir build
cd build
cmake ..
make 
```

got output
```
hjianhao@ubuntu:~/code/github/leela-zero/src$ cd ..
hjianhao@ubuntu:~/code/github/leela-zero$ ls
AUTHORS  best_v1.txt.zip  CMakeLists.txt  FAQ.md  README.md  src
autogtp  cmake            COPYING         msvc    scripts    training
hjianhao@ubuntu:~/code/github/leela-zero$ mkdir build
hjianhao@ubuntu:~/code/github/leela-zero$ cd build
hjianhao@ubuntu:~/code/github/leela-zero/build$ cmake ..
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1753 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.58 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:24 (FIND_PACKAGE)


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "1.2")
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- Configuring incomplete, errors occurred!
See also "/home/hjianhao/code/github/leela-zero/build/CMakeFiles/CMakeOutput.log".
See also "/home/hjianhao/code/github/leela-zero/build/CMakeFiles/CMakeError.log".
hjianhao@ubuntu:~/code/github/leela-zero/build$ make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by hjianhao** [comment] 2017-12-10 13:28
Had you tested in Ubuntu 14.04?

I also found some bugs in your instructions. for example

unzip https://sjeng.org/zero/best_v1.txt.zip
This should be 
unzip best_v1.txt.zip
?

**Comment by qysnn** [comment] 2017-12-10 13:29
How about try `sudo apt update` and `sudo apt upgrade` then compile with cmake again?

**Comment by hjianhao** [comment] 2017-12-10 13:32
The macOS instructions also not worked in newest macOS

because brew link not worked.

I had done the following steps, before I can compile the leela-zero

```
sudo mkdir /usr/local/include
sudo chown -R $(whoami) $(brew --prefix)/*
brew link boost
```

**Comment by hjianhao** [comment] 2017-12-10 13:33
@qysnn I had done sudo apt update and sudo apt upgrade before I start to compile.

**Comment by marcocalignano** [comment] 2017-12-10 14:25
@hjianhao Ubuntu 14.04 is old! The last last LTS from Ubuntu is 1604 and if you update to ubuntu 16.04 then you get even libboost 1.58, then everything will work!

**Comment by hjianhao** [comment] 2017-12-10 14:34
@marcocalignano  seems it's not the problem about libboost, it's the openblas's problem. I install OpenBLAS manually, then I can compile leela(not upgrade the libboost).  And after I installed Display driver, I can run leela properly. For some reason, I can not upgrade my Linux system to 1604.


But when I compile autogtp, I got hundreds of errors. One of them as following 

```
/usr/include/qt5/QtCore/qstring.h:220:5: note:   conversion of argument 2 would be ill-formed:
main.cpp:56:25: error: conversion from ‘const char [8]’ to ‘QChar’ is ambiguous
               "filename");
                         ^
In file included from /usr/include/qt5/QtCore/qstring.h:45:0,
                 from /usr/include/qt5/QtCore/qcoreapplication.h:46,
                 from /usr/include/qt5/QtCore/QCoreApplication:1,
                 from main.cpp:19:
```
and I had done the steps before compile.

```
    sudo apt install qt5-default qt5-qmake curl
    qmake -qt5
    make
```

**Comment by isty2e** [comment] 2017-12-10 14:46
Is there any non-standard configuration you are using? I had no trouble compling following the instruction using mac also. And I have no idea why openblas installed with apt was not properly detected.

**Comment by hjianhao** [comment] 2017-12-10 14:50
@isty2e  for mac, because I used newest macOS, so following the instruction not ok, I add 3 steps for brew boost link , then I can start auto training 

For Ubuntu 14.04, according to @marcocalignano , it's too old ubuntu version, I meet bunch of problems. Now I had compiled and ran leela, but compile autogtp still got errors, I am trying to resolved it.

**Comment by marcocalignano** [comment] 2017-12-10 18:24
@hjianhao  wihch QT version do you have?

**Comment by hjianhao** [comment] 2017-12-11 01:12
@marcocalignano  qmake 3.0  QT lib 5.2.1

**Comment by marcocalignano** [comment] 2017-12-14 22:05
@hjianhao you need at least QT 5.3 try to find a ppa for a newer QT version

**Comment by tonyxia2016** [comment] 2017-12-26 10:01
@hjianhao Installed QT 5.7 https://wiki.qt.io/Install_Qt_5_on_Ubuntu , then run the qmake of the QT 5.7, the autogtp can be compiled successfully in Ubuntu 14. 
However, during the running of the autogtp, it stalls at the curl line forever

**Comment by marcocalignano** [comment] 2017-12-26 11:40
Is curl installed?

**Comment by tonyxia2016** [comment] 2017-12-26 12:15
@marcocalignano  Now the curl issue is solved, maybe it is a network or curl version issue. Anyway , I upgrade the curl to 7.57.0 version. And the curl issue is gone.
However, now the issue is leelaz on my Ubuntu 14.

Here is the log.
=========
Already downloaded network.
./leelaz -r 1 -g -t 1 -q -d -n -m 30 -w c99f1ae0531adc89303492983a621bae88b68a7782e77046e5bde0b520a63986 -p 1600 --noponder
*ERROR*: Could not talk to engine after launching.

p$ ./leelaz 
./leelaz: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by ./leelaz)
./leelaz: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by ./leelaz)
A network weights file is required to use the program.
~/leela-zero/autogtp$ ./leelaz -w c99f1ae0531adc89303492983a621bae88b68a7782e77046e5bde0b520a63986 
./leelaz: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by ./leelaz)
./leelaz: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by ./leelaz)
Using 2 thread(s).
RNG seed: 6331342031055775448
Leela Zero  Copyright (C) 2017  Gian-Carlo Pascutto
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Initializing OpenCL
Detected 1 OpenCL platforms
Platform version: OpenCL 1.2 CUDA 9.0.194
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 1080
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 384.90
Device speed:  1784 MHz
Device cores:  20 CU
Device score:  1112
Device ID:     1
Device name:   GeForce GTX 1080
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 384.90
Device speed:  1784 MHz
Device cores:  20 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1080
with OpenCL 1.2 capability
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Detecting residual layers...v1...64 channels...5 blocks
Transferring weights to GPU...done
./leelaz: symbol lookup error: ./leelaz: undefined symbol: openblas_get_corename

**Comment by marcocalignano** [comment] 2017-12-26 12:17
try this please:
`./leelaz -r 1 -g -t 1 -q -d -n -m 30 -w c99f1ae0531adc89303492983a621bae88b68a7782e77046e5bde0b520a63986 -p 1600 --noponder`

**Comment by tonyxia2016** [comment] 2017-12-26 12:21
$ ./leelaz -r 1 -g -t 1 -q -d -n -m 30 -w c99f1ae0531adc89303492983a621bae88b68a7782e77046e5bde0b520a63986 -p 1600 --noponder
./leelaz: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by ./leelaz)
./leelaz: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by ./leelaz)
./leelaz: symbol lookup error: ./leelaz: undefined symbol: openblas_get_corename

**Comment by marcocalignano** [comment] 2017-12-26 12:37
Try the following 
```
leela-zero$ mkdir build
leela-zero$ cd build
leela-zero/build$ cmake ..

```

**Comment by gcp** [comment] 2017-12-26 13:17
Your OpenBLAS installation either has a version without that symbol OR your system supports multiple alternative BLAS libraries and it is supplying Leela with one that is not OpenBLAS or the wrong OpenBLAS version.

The warnings about libOpenCL.so.1 are harmless. It's a bug in NVIDIA's OpenCL ICD loader.

**Comment by tonyxia2016** [comment] 2017-12-26 14:43
/build$ cmake ..
CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1928 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.58 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:24 (FIND_PACKAGE)


-- A library with BLAS API found.
-- Configuring incomplete, errors occurred!
See also "/home/hust-406/leela-zero-0.9/build/CMakeFiles/CMakeOutput.log".
See also "/home/hust-406/leela-zero-0.9/build/CMakeFiles/CMakeError.log".

**Comment by marcocalignano** [comment] 2017-12-27 09:42
Like I said 14.04 is old, 16.04 is the last stable ubuntu. You need to upgrade your distribution or install all the new library yourself.

**Comment by bood** [comment] 2017-12-27 11:22
@tonyxia2016 Here is a working version for ubuntu 14 that I tested on Travis:
```
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo add-apt-repository ppa:kojoley/boost -y
  - sudo apt-get update -q
  - sudo apt-get install boost1.58-dev libboost-program-options1.58-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev qt55base qt55tools -y
  - sudo apt-get install g++-6 gfortran -y

install:
  - git clone https://github.com/xianyi/OpenBLAS.git
  - cd OpenBLAS && git checkout tags/v0.2.20
  - mkdir build && cd build && cmake ..
  - make --silent -j3 && sudo make install
  - cd ../..

script:
  - source /opt/qt55/bin/qt55-env.sh
```

**Closed** 2019-02-14 05:27 UTC
Labels: techsupport
