### ISSUE TITLE
Fully connected layer of policy head, and block size

### ISSUE THREAD

**Issue by tamubun** [leela-zero/leela-zero#658] opened 2018-01-16 13:45 UTC
In [https://github.com/gcp/leela-zero/issues/514](https://github.com/gcp/leela-zero/issues/514) gcp said
> 4. The policy and value heads contain a fully connected layer that spans the entire 19 x 19 board.
>
> So the answer to the original question is a clear no: she can see much further.

But I don't think the fully connected layer of policy head is nothing to do with the global span of the board. I think AGZ team inserted this layer for the purpose only to generate a probability for PASS move as well as other moves in the same ground.

To confirm my belief, I checked the weight of this fully connected layer in 0db82470 and found that considerable weights that affect some output for point P locate almost around P, other weights far from P are nearly 0. On the other hands for an output PASS, all weights near border has some big value (this is interesting non border weights are almost 0). So the weights are very local except for an output PASS.

Return to the ladder issue, I think residual block size 6 (i.e. convolution layer 13) is minimal not enough, since fully connected layer does not help at all. And if we concern some big stone group which size is larger than 13, network cannot distinguish that group has only 1 liberty or not if the block size is 6. This is critical because life or death of large group leads directly to the game end.

**Comment by Marcin1960** [comment] 2018-01-16 13:52
If so, what is the minimum size for ladder issue solution?

**Comment by tamubun** [comment] 2018-01-16 13:55
I think 9 block (9*2+1 = 19) is minimal.

**Comment by gcp** [comment] 2018-01-16 14:04
>I think AGZ team inserted this layer for the purpose only to generate a probability for PASS move as well as other moves in the same ground.

Not arguing that - there's been a discussion on computer-go about the use of having a fully-connected layer just for this.

The layer has the possibility to see the full board, that does not mean it will do so. (You could argue it actually does do so to help to decide when to pass or not!)

>And if we concern some big stone group which size is larger than 13, network cannot distinguish that group has only 1 liberty or not if the block size is 6.

I don't see how this follows at all. Did you mean to say, in case the group is *spatially* spread out throughout the full board, like in a ladder? In that case the original post explains why you are off by a factor ~2, although the ability to find them arbitrarily does increase greatly around 9-10 blocks. Nobody is arguing that either.

**Comment by tapsika** [comment] 2018-01-16 14:20
I think #3 in that post (propagate in opposite directions) is what is the most problematic. IMO it is just a theoretical possibility with little practical consequence (for the current filter counts): it is unreasonable to expect that with the same number of filters, central squares could do BOTH their normal work AND solve all long ladders for all positions.

On the other hand, early AG had 12 layers only, with no apparent ladder problem - probably relying on search techniques for very long ladders?

**Comment by jkiliani** [comment] 2018-01-16 14:25
Extended data table 2 in the original Alphago paper (January 2016) shows "Ladder capture" and "Ladder escape" as feature planes for both policy and value network. So their 12 layers did not solve ladders by themselves, Deepmind had to handcraft them to work correctly with their neural network.

**Comment by gcp** [comment] 2018-01-16 14:26
>it is unreasonable to expect that with the same number of filters, central squares could do BOTH their normal work AND solve all long ladders for all positions

I agree, that's why I made the point about "arbitrarily". Of the 64 filters, some could be spent trying to find the most common ladders that lead to a lot of losses, but it certainly will not be able to spot all ladders with some degree of confidence.

The question was whether a 5 layer (even though probably "blocks" was intended!) network can see further than 5 squares, and the answer is and will always be a clear yes. That does not mean it can trivially see all kinds of things 19 squares away and nobody is making that claim. You are preaching to the choir here.

>On the other hand, early AG had 12 layers only, with no apparent ladder problem - probably relying on search techniques for very long ladders?

They had specific ladder detection and used that as inputs.

**Comment by gcp** [comment] 2018-01-16 14:27
>So their 12 layers did not solve ladders by themselves, Deepmind had to handcraft them to work correctly with their neural network.

Don't forget that they were using supervised learning. Their input data had no ladders at all, so even 40 blocks would not have helped anything.

**Comment by tapsika** [comment] 2018-01-16 14:40
> They had specific ladder detection and used that as inputs.

Yes of course, I forgot for a moment. But that may still leave some problems with LD of large dragons (though maybe some other handcrafted stuff was useful in that respect as well).

**Comment by tamubun** [comment] 2018-01-16 14:59
I didn't follow discussion about full connected layer and I agree that I only saw current LZ's network weight, but I can't imagine what weight of full connected layer could treat global board sturucture.

> I don't see how this follows at all. Did you mean to say, in case the group is spatially spread out throughout the full board, like in a ladder? In that case the original post explains why you are off by a factor ~2, although the ability to find them arbitrarily does increase greatly around 9-10 blocks. Nobody is arguing that either, in fact see what I literally wrote 4 hours ago: #591 (comment)

Yes, in the last paragraph I posted, the size of group (i want to say) is spatially spreading size. If opponents move is something like ladder atari for big group, but the other side of this group has many liberty, that opponents move is not atari. But if networks eyesight is limited by the residual blocks size, then network cannot distinguish the big group is in danger or not. (Block size 6 means convolution layer 13, so network can see 13 spatially separated point)

**Comment by gcp** [comment] 2018-01-16 15:24
>Yes of course, I forgot for a moment. But that may still leave some problems with LD of large dragons (though maybe some other handcrafted stuff was useful in that respect as well).

IMHO one potential problem of those is that you end up having a one input that says "group has more than x liberties" and this may make it harder for the network to learn the difference between x and x + 1, which may be important for large dragons.

It doesn't help that large dragons never die in pro games. (The pro resigns before that point)

>Block size 6 means convolution layer 13, so network can see 13 spatially separated point

More or less directly, yes. It can see twice as far, but only indirectly (by going to the center). Note that even seeing it directly is really not all that trivial for the learning, you have to construct a chain of weights that moves consistently in the right direction also.

**Comment by tamubun** [comment] 2018-01-16 17:19
> More or less directly, yes. It can see twice as far, but only indirectly (by going to the center from both ends).

What means indirect?

For example the case 64 filter x 5 blocks, the outputs of topmost residual blocks are 64 feature planes. Take one feature plane arbitrary, and see the value at point say C3 of that plane. Since point C3 is spatially separated from point C17 more than 10 distance, the value is independent of any value at C17 in all input planes. I understand output value at midpoint C10 is affected both input value at C3 and C17, but that value do not affect C3 value. Yes, full connected layer has ability to relate these independent values, but I'm still doubtful about that.

**Comment by tamubun** [comment] 2018-01-17 06:24
Now I think I understand the meaning of "indirect" watching a LZ [self play](http://zero.sjeng.org/view/bda3e3b45eddb26e47df68c648027a7094c3be7cb8acf85f1ae1f13e9698c17f?viewer=wgo) at move 185.

The big white group at H7 is in danger, but it is spatially spread 12 width. Previous opponents move G7 is far from urgent point T3. When LZ network views around midpoint N7 or so, it can see both sides and realize the urgency and change value T3 much higher.

I change my idea about minimal block size to 5 from 9. Convolution layer 5*2+1 is sufficient "indirectly".

**Comment by tamubun** [comment] 2018-01-17 08:33
Sorry for posting many times. I'm confused and mistaken.

Even if LZ can see both side when she see around N7 and realize the urgency, she cannot change the value T3. She only change the value around N7 and that value do not far to T3 if block size is small.

I don't know why LZ luckily found T3 at move 185, but I think that behavior is not because "indirect" relation.

**Comment by gcp** [comment] 2018-01-17 08:41
2 possibilities:

1) Increasing the urgency around N7 can still propagate to at least T3's neigbours, which still influences the FC layer.
2) The tree search can probably see that it is forcing, so the network doesn't have to see the full sequence, it just has to score attacking/defending moves on the group high enough.

**Comment by tamubun** [comment] 2018-01-17 13:43
I think possibility 2 is more feasible. When I have time, I will check.

**Comment by killerducky** [comment] 2018-01-17 14:16
@tamubun I understand where you're coming from but this example is not good. T3 is not urgent, black cannot play Q1 or T1. So in fact White playing T3 is a mistake. Note also White has a massive lead in this game so almost anything it does that is safe is good enough, including playing the "wrong" move T3.

**Comment by tamubun** [comment] 2018-01-18 14:09
Well, I think above example is somewhat bad, I understand in real game T3 is not urgent, but I thought "LZ found T3 was urgent by previous black move G7" and I thought this was good example to show LZ can understand long spanned distance by seeing midpoint. But now I admit as you say, maybe LZ moved T3 only she want to pick up a right down black group.

**Comment by tamubun** [comment] 2018-01-18 14:10
Well, I think above example is somewhat bad, I understand in real game T3 is not urgent, but I thought "LZ found T3 was urgent by previous black move G7" and I thought this was good example to show LZ can understand long spanned distance by seeing midpoint. But now I admit as you say, maybe LZ moved T3 only she want to pick up a bottom right black group.

**Comment by sethtroisi** [comment] 2019-02-14 05:42
No active discussion for >1 year, closing

**Closed by sethtroisi** 2019-02-14 05:42 UTC
Labels: question
