### ISSUE TITLE
Assertion error in uctsearch.cpp

### ISSUE THREAD

**Issue by Cabu** [leela-zero/leela-zero#1155] opened 2018-04-05 15:07 UTC
Assertion failed: pruned_nodes < m_root->get_children().size(), file d:\sources\c++\leela-zero\src\uctsearch.cpp, line 475

Command line: leela-zero.exe -w leelaz-model.txt --gtp --lagbuffer 150 --threads 1 --visits 2500 --resignpct -1 --quiet

This has been triggered during a game on KGS. But I don't know when exactly :(

**Comment by gcp** [comment] 2018-04-05 15:33
Any more details? Command line options? Commands given?

**Comment by killerducky** [comment] 2018-04-05 15:56
I meant to post here but forgot. While porting timemanage to LCZero I noticed that assertion could theoretically fire if some races happen with multiple threads. The code finds Nfirst and then prunes based on that, but doesn't lock the stats. So maybe it could end up pruning every node?

I actually hit the assertion once, but it ended up being due to a mistake in my code. Before finding my bug I noticed this possibility. I don't think I ever actually proved this is a real case.

I removed it in my pull request to LCZero.
https://github.com/glinscott/leela-chess/pull/217

**Comment by gcp** [comment] 2018-04-05 16:08
I don't see how it can happen? Nfirst is calculated first and set [1]. Even if the other threads keep going on, that just means node->get_visits() will have bigger numbers and compare favorably to min_required_visits.

[1] It's looping over the children without taking a lock, which is unsafe, though.

**Comment by gcp** [comment] 2018-04-05 16:14
One possible scenario: est_playouts_left returns a negative value (it's not clamed to 0).

This can happen because that is assuming m_maxplyouts and m_maxvisits are never exceeded, but that can happen with multiple threads.

**Comment by killerducky** [comment] 2018-04-05 16:34
Aha good, I'll make the same change to my LCZero PR and put the assert back.

**Comment by gcp** [comment] 2018-04-05 16:55
I'm not sure this fixes the original problem (not enough info) but from a quick look this seemed like a case that can go wrong. Can't hurt to clamp there in any case.

**Comment by Cabu** [comment] 2018-04-05 16:58
Original comment updated.

**Comment by gcp** [comment] 2018-04-06 13:25
Hmm, was with --threads 1, so the underlying issue would still exist.

**Comment by killerducky** [comment] 2018-04-06 13:50
@Cabu can you add "-l logfile.txt" to the command line? Maybe KGS is sending kgs_time_settings at weird times, like when LZ already started thinking? Or we might see some other unexpected behavior.

**Comment by Cabu** [comment] 2018-04-07 09:02
The thing is that I have seen that error only once on 100ed of games played on KGS. I run my bot during that last 8hous without problems. The probability to reoccur is very low :(

**Comment by sethtroisi** [comment] 2019-02-14 06:16
closing, no active discussion for ~1year and many code changes since

**Closed by sethtroisi** 2019-02-14 06:16 UTC
