### ISSUE TITLE
Error Compiling 0.16 on Mac

### ISSUE THREAD

**Issue by trunterzx** [leela-zero/leela-zero#1977] opened 2018-11-01 15:46 UTC
Thank you very much for the new release!

Can't wait to see what the latest version looks like, so I just tried compiling the latest version of Leela Zero (0.16) on my Mac.

I followed the example for the compiling for Mac written in the readme, but there was an error at the following line:

`cmake --build .`

The error message was as follows:

> "The vecLib framework is deprecated. Please include
>       <Accelerate/Accelerate.h> instead of <vecLib/vecLib.h> and link to the
>       Accelerate framework instead of the vecLib framework."

Is there something that is missing from my Mac, or do I need to make changes somewhere?

Any help would be very much appreciated!

Below is my whole log for the compilation up to the point of error.

> MacBys-iMac:~ MacBy$ # Clone github repo
> MacBys-iMac:~ MacBy$ git clone https://github.com/gcp/leela-zero
> Cloning into 'leela-zero'...
> remote: Enumerating objects: 4400, done.
> remote: Total 4400 (delta 0), reused 0 (delta 0), pack-reused 4400
> Receiving objects: 100% (4400/4400), 3.24 MiB | 1.77 MiB/s, done.
> Resolving deltas: 100% (3159/3159), done.
> MacBys-iMac:~ MacBy$ cd leela-zero
> MacBys-iMac:leela-zero MacBy$ git submodule update --init --recursive
> Submodule 'gtest' (https://github.com/google/googletest.git) registered for path 'gtest'
> Submodule 'src/Eigen' (https://github.com/eigenteam/eigen-git-mirror) registered for path 'src/Eigen'
> Cloning into '/Users/MacBy/leela-zero/gtest'...
> Cloning into '/Users/MacBy/leela-zero/src/Eigen'...
> Submodule path 'gtest': checked out 'cafa9e52285d743d1394900fa95662950f712a72'
> Submodule path 'src/Eigen': checked out 'a1b9c26c5e62cb8c17836e601edd64b92aa8e5ae'
> MacBys-iMac:leela-zero MacBy$ 
> MacBys-iMac:leela-zero MacBy$ # Install build depedencies
> MacBys-iMac:leela-zero MacBy$ brew install boost cmake
> Updating Homebrew...
> ==> Auto-updated Homebrew!
> Updated 1 tap (homebrew/core).
> ==> New Formulae
> fluxctl
> ==> Updated Formulae
> diff-pdf            pdftoedn            pdftoipe            poppler
> 
> Warning: boost 1.67.0_1 is already installed and up-to-date
> To reinstall 1.67.0_1, run `brew reinstall boost`
> Warning: cmake 3.12.3 is already installed and up-to-date
> To reinstall 3.12.3, run `brew reinstall cmake`
> MacBys-iMac:leela-zero MacBy$ 
> MacBys-iMac:leela-zero MacBy$ # Use stand alone directory to keep source dir clean
> MacBys-iMac:leela-zero MacBy$ mkdir build && cd build
> MacBys-iMac:build MacBy$ cmake ..
> -- The C compiler identification is AppleClang 10.0.0.10001044
> -- The CXX compiler identification is AppleClang 10.0.0.10001044
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
> -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - found
> -- Found Threads: TRUE  
> -- Boost version: 1.67.0
> -- Found the following Boost libraries:
> --   program_options
> --   filesystem
> --   system
> -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
> -- Looking for CL_VERSION_2_2
> -- Looking for CL_VERSION_2_2 - not found
> -- Looking for CL_VERSION_2_1
> -- Looking for CL_VERSION_2_1 - not found
> -- Looking for CL_VERSION_2_0
> -- Looking for CL_VERSION_2_0 - not found
> -- Looking for CL_VERSION_1_2
> -- Looking for CL_VERSION_1_2 - found
> -- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (found version "1.2") 
> -- Using built-in matrix library.
> CMake Warning at CMakeLists.txt:50 (find_package):
>   By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5Core", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Core" with any
>   of the following names:
> 
>     Qt5CoreConfig.cmake
>     qt5core-config.cmake
> 
>   Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
>   "Qt5Core_DIR" to a directory containing one of the above files.  If
>   "Qt5Core" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> CMake Warning at CMakeLists.txt:129 (message):
>   Qt is not found, build for `autogtp` and `validation` is disabled
> 
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/MacBy/leela-zero/build
> MacBys-iMac:build MacBy$ cmake --build .
> Scanning dependencies of target gtest
> [  2%] Building CXX object gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
> [  5%] Linking CXX static library libgtest.a
> [  5%] Built target gtest
> Scanning dependencies of target objs
> [  8%] Building CXX object CMakeFiles/objs.dir/src/CPUPipe.cpp.o
> warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean
>       '-Wno-uninitialized'? [-Wunknown-warning-option]
> In file included from /Users/MacBy/leela-zero/src/CPUPipe.cpp:22:
> In file included from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20:
> /System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers/../Frameworks/vecLib.framework/Headers/vecLib.h:1:2: error: 
>       "The vecLib framework is deprecated. Please include
>       <Accelerate/Accelerate.h> instead of <vecLib/vecLib.h> and link to the
>       Accelerate framework instead of the vecLib framework."
> #error "The vecLib framework is deprecated. Please include <Accelerate/A...
>  ^
> In file included from /Users/MacBy/leela-zero/src/CPUPipe.cpp:35:
> In file included from /Users/MacBy/leela-zero/src/Network.h:35:
> In file included from /Users/MacBy/leela-zero/src/OpenCLScheduler.h:28:
> In file included from /Users/MacBy/leela-zero/src/OpenCL.h:27:
> /Users/MacBy/leela-zero/src/CL/cl2.hpp:4581:25: warning: 'clCreateImage2D' is
>       deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
>             object_ = ::clCreateImage2D(
>                         ^
> /System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1170:1: note: 
>       'clCreateImage2D' has been explicitly marked deprecated here
> clCreateImage2D(cl_context              /* context */,
> ^
> In file included from /Users/MacBy/leela-zero/src/CPUPipe.cpp:35:
> In file included from /Users/MacBy/leela-zero/src/Network.h:35:
> In file included from /Users/MacBy/leela-zero/src/OpenCLScheduler.h:28:
> In file included from /Users/MacBy/leela-zero/src/OpenCL.h:27:
> /Users/MacBy/leela-zero/src/CL/cl2.hpp:5014:25: warning: 'clCreateImage3D' is
>       deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
>             object_ = ::clCreateImage3D(
>                         ^
> /System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1180:1: note: 
>       'clCreateImage3D' has been explicitly marked deprecated here
> clCreateImage3D(cl_context              /* context */,
> ^
> In file included from /Users/MacBy/leela-zero/src/CPUPipe.cpp:35:
> In file included from /Users/MacBy/leela-zero/src/Network.h:35:
> In file included from /Users/MacBy/leela-zero/src/OpenCLScheduler.h:28:
> In file included from /Users/MacBy/leela-zero/src/OpenCL.h:27:
> /Users/MacBy/leela-zero/src/CL/cl2.hpp:5104:21: warning: 
>       'clCreateFromGLTexture3D' is deprecated: first deprecated in macOS 10.8
>       [-Wdeprecated-declarations]
>         object_ = ::clCreateFromGLTexture3D(
>                     ^
> /System/Library/Frameworks/OpenCL.framework/Headers/cl_gl.h:116:1: note: 
>       'clCreateFromGLTexture3D' has been explicitly marked deprecated here
> clCreateFromGLTexture3D(cl_context      /* context */,
> ^
> /Users/MacBy/leela-zero/src/CPUPipe.cpp:64:54: warning: suggest braces around
>       initialization of subobject [-Wmissing-braces]
>     std::array<std::array<float, Wpad>, Wpad> in_pad{0.0f};
>                                                      ^~~~
>                                                      {   }
> 5 warnings and 1 error generated.
> make[2]: *** [CMakeFiles/objs.dir/src/CPUPipe.cpp.o] Error 1
> make[1]: *** [CMakeFiles/objs.dir/all] Error 2
> make: *** [all] Error 2
> MacBys-iMac:build MacBy$

**Comment by maxinjapan** [comment] 2018-11-01 20:05
hi @trunterzx. it seems it compiles fine on my mac. 

Have you tried `brew update boost cmake` instead of install?

**Comment by gcp** [comment] 2018-11-02 09:21
> Please include
<Accelerate/Accelerate.h> instead of <vecLib/vecLib.h>

Note that our code already does ```#include <Accelerate/Accelerate.h>```.

**Comment by trunterzx** [comment] 2018-11-02 14:33
@maxinjapan 

Thank you for the suggestion.

`brew update boost cmake` didn't seem to work as it asked me to run `brew upgrade boost cmake` instead.
So I tried running that, but I still got the same error :(


@gcp 

Thank you for the suggestion.

I'm sorry but where should I add the line `-DUSE_BLAS`?

**Comment by as0770** [comment] 2018-11-02 17:55
Similar problem in Ubuntu 18.04:

[  3%] Building CXX object CMakeFiles/objs.dir/src/CPUPipe.cpp.o
/leela-zero-0.16/src/CPUPipe.cpp:31:10: fatal error: Eigen/Dense: Datei oder Verzeichnis nicht gefunden
 #include <Eigen/Dense>

**Comment by gcp** [comment] 2018-11-05 09:59
>Similar problem in Ubuntu 18.04:
>fatal error: Eigen/Dense: Datei oder Verzeichnis nicht gefunden
#include <Eigen/Dense>

This is a different problem: you did not read the README.

**Comment by gcp** [comment] 2018-11-05 14:46
>I'm sorry but where should I add the line -DUSE_BLAS?

Where you do

```cmake ..```

do

```cmake -DUSE_BLAS=1 ..``` instead.

**Comment by gcp** [comment] 2018-11-05 14:48
FWIW I can't reproduce this problem on any of my Macs.

**Comment by trunterzx** [comment] 2018-11-10 10:37
@gcp Thanks for the suggestion!

> Where you do
> 
> cmake ..
> 
> do
> 
> cmake -DUSE_BLAS=1 .. instead.

However, after doing the above I have 7 errors now...

Please refer to all the output below.
I will try using my other Mac to see whether it works or not.


> Last login: Sat Nov 10 18:31:00 on ttys000
> MacBys-iMac:~ MacBy$ git clone https://github.com/gcp/leela-zero
> Cloning into 'leela-zero'...
> remote: Enumerating objects: 4416, done.
> remote: Total 4416 (delta 0), reused 0 (delta 0), pack-reused 4416
> Receiving objects: 100% (4416/4416), 3.24 MiB | 2.21 MiB/s, done.
> Resolving deltas: 100% (3171/3171), done.
> MacBys-iMac:~ MacBy$ cd leela-zero
> MacBys-iMac:leela-zero MacBy$ git submodule update --init --recursive
> Submodule 'gtest' (https://github.com/google/googletest.git) registered for path 'gtest'
> Submodule 'src/Eigen' (https://github.com/eigenteam/eigen-git-mirror) registered for path 'src/Eigen'
> Cloning into '/Users/MacBy/leela-zero/gtest'...
> Cloning into '/Users/MacBy/leela-zero/src/Eigen'...
> Submodule path 'gtest': checked out 'cafa9e52285d743d1394900fa95662950f712a72'
> Submodule path 'src/Eigen': checked out 'a1b9c26c5e62cb8c17836e601edd64b92aa8e5ae'
> MacBys-iMac:leela-zero MacBy$ brew install boost cmake
> Warning: boost 1.68.0 is already installed and up-to-date
> To reinstall 1.68.0, run `brew reinstall boost`
> Warning: cmake 3.12.4 is already installed and up-to-date
> To reinstall 3.12.4, run `brew reinstall cmake`
> MacBys-iMac:leela-zero MacBy$ mkdir build && cd build
> MacBys-iMac:build MacBy$ cmake -DUSE_BLAS=1 ..
> -- The C compiler identification is AppleClang 10.0.0.10001145
> -- The CXX compiler identification is AppleClang 10.0.0.10001145
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - found
> -- Found Threads: TRUE  
> -- Boost version: 1.68.0
> -- Found the following Boost libraries:
> --   program_options
> --   filesystem
> --   system
> -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
> -- Looking for CL_VERSION_2_2
> -- Looking for CL_VERSION_2_2 - not found
> -- Looking for CL_VERSION_2_1
> -- Looking for CL_VERSION_2_1 - not found
> -- Looking for CL_VERSION_2_0
> -- Looking for CL_VERSION_2_0 - not found
> -- Looking for CL_VERSION_1_2
> -- Looking for CL_VERSION_1_2 - found
> -- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (found version "1.2") 
> -- Looking for system BLAS/OpenBLAS library.
> -- Looking for dgemm_
> -- Looking for dgemm_ - found
> -- A library with BLAS API found.
> CMake Warning at CMakeLists.txt:50 (find_package):
>   By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5Core", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Core" with any
>   of the following names:
> 
>     Qt5CoreConfig.cmake
>     qt5core-config.cmake
> 
>   Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
>   "Qt5Core_DIR" to a directory containing one of the above files.  If
>   "Qt5Core" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> CMake Warning at CMakeLists.txt:129 (message):
>   Qt is not found, build for `autogtp` and `validation` is disabled
> 
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/MacBy/leela-zero/build
> MacBys-iMac:build MacBy$ cmake --build .
> Scanning dependencies of target gtest
> [  2%] Building CXX object gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
> [  5%] Linking CXX static library libgtest.a
> [  5%] Built target gtest
> Scanning dependencies of target objs
> [  8%] Building CXX object CMakeFiles/objs.dir/src/CPUPipe.cpp.o
> warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean
>       '-Wno-uninitialized'? [-Wunknown-warning-option]
> In file included from /Users/MacBy/leela-zero/src/CPUPipe.cpp:22:
> In file included from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20:
> /System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers/../Frameworks/vecLib.framework/Headers/vecLib.h:1:2: error: 
>       "The vecLib framework is deprecated. Please include
>       <Accelerate/Accelerate.h> instead of <vecLib/vecLib.h> and link to the
>       Accelerate framework instead of the vecLib framework."
> #error "The vecLib framework is deprecated. Please include <Accelerate/A...
>  ^
> In file included from /Users/MacBy/leela-zero/src/CPUPipe.cpp:35:
> In file included from /Users/MacBy/leela-zero/src/Network.h:35:
> In file included from /Users/MacBy/leela-zero/src/OpenCLScheduler.h:28:
> In file included from /Users/MacBy/leela-zero/src/OpenCL.h:27:
> /Users/MacBy/leela-zero/src/CL/cl2.hpp:4581:25: warning: 'clCreateImage2D' is
>       deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
>             object_ = ::clCreateImage2D(
>                         ^
> /System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1170:1: note: 
>       'clCreateImage2D' has been explicitly marked deprecated here
> clCreateImage2D(cl_context              /* context */,
> ^
> In file included from /Users/MacBy/leela-zero/src/CPUPipe.cpp:35:
> In file included from /Users/MacBy/leela-zero/src/Network.h:35:
> In file included from /Users/MacBy/leela-zero/src/OpenCLScheduler.h:28:
> In file included from /Users/MacBy/leela-zero/src/OpenCL.h:27:
> /Users/MacBy/leela-zero/src/CL/cl2.hpp:5014:25: warning: 'clCreateImage3D' is
>       deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
>             object_ = ::clCreateImage3D(
>                         ^
> /System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1180:1: note: 
>       'clCreateImage3D' has been explicitly marked deprecated here
> clCreateImage3D(cl_context              /* context */,
> ^
> In file included from /Users/MacBy/leela-zero/src/CPUPipe.cpp:35:
> In file included from /Users/MacBy/leela-zero/src/Network.h:35:
> In file included from /Users/MacBy/leela-zero/src/OpenCLScheduler.h:28:
> In file included from /Users/MacBy/leela-zero/src/OpenCL.h:27:
> /Users/MacBy/leela-zero/src/CL/cl2.hpp:5104:21: warning: 
>       'clCreateFromGLTexture3D' is deprecated: first deprecated in macOS 10.8
>       [-Wdeprecated-declarations]
>         object_ = ::clCreateFromGLTexture3D(
>                     ^
> /System/Library/Frameworks/OpenCL.framework/Headers/cl_gl.h:116:1: note: 
>       'clCreateFromGLTexture3D' has been explicitly marked deprecated here
> clCreateFromGLTexture3D(cl_context      /* context */,
> ^
> /Users/MacBy/leela-zero/src/CPUPipe.cpp:64:54: warning: suggest braces around
>       initialization of subobject [-Wmissing-braces]
>     std::array<std::array<float, Wpad>, Wpad> in_pad{0.0f};
>                                                      ^~~~
>                                                      {   }
> /Users/MacBy/leela-zero/src/CPUPipe.cpp:144:21: error: use of undeclared
>       identifier 'CblasRowMajor'
>         cblas_sgemm(CblasRowMajor, CblasTrans, CblasNoTrans,
>                     ^
> /Users/MacBy/leela-zero/src/CPUPipe.cpp:144:36: error: use of undeclared
>       identifier 'CblasTrans'
>         cblas_sgemm(CblasRowMajor, CblasTrans, CblasNoTrans,
>                                    ^
> /Users/MacBy/leela-zero/src/CPUPipe.cpp:144:48: error: use of undeclared
>       identifier 'CblasNoTrans'
>         cblas_sgemm(CblasRowMajor, CblasTrans, CblasNoTrans,
>                                                ^
> /Users/MacBy/leela-zero/src/CPUPipe.cpp:273:17: error: use of undeclared
>       identifier 'CblasRowMajor'
>     cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
>                 ^
> /Users/MacBy/leela-zero/src/CPUPipe.cpp:273:32: error: use of undeclared
>       identifier 'CblasNoTrans'
>     cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
>                                ^
> /Users/MacBy/leela-zero/src/CPUPipe.cpp:273:46: error: use of undeclared
>       identifier 'CblasNoTrans'
>     cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
>                                              ^
> 5 warnings and 7 errors generated.
> make[2]: *** [CMakeFiles/objs.dir/src/CPUPipe.cpp.o] Error 1
> make[1]: *** [CMakeFiles/objs.dir/all] Error 2
> make: *** [all] Error 2
> MacBys-iMac:build MacBy$

**Comment by kwccoin** [comment] 2018-11-18 10:09
Mine is not ok.   Is there any particular version needed?  Due to the use of CUDA, I have to use Mac OS 10.13.6, Xcode 9.4 and CUDA related series.  CUDA Sample work but so far  not Leela-zero:

`cmake -DUSE_BLAS=1 ..
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
-- Looking for system BLAS/OpenBLAS library.
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- A library with BLAS API found.
-- Configuring done
CMake Error in autogtp/CMakeLists.txt:
  No known features for CXX compiler

  "AppleClang"

  version 10.0.0.10001044.

`

Any help would be appreciated as bootcamp of 10.13.6 and Win 10 does not work well together and hence that works for using lizzie is not a long term solution for me.

**Comment by kwccoin** [comment] 2018-11-18 14:03
I look at the directory issue of the windows and move all my compilation to ~ and it all works.

**Comment by saweiss** [comment] 2018-11-29 01:06
For what it's worth, I was only able to compile and successfully run LZ 0.16 on macOS 10.13.6, iMac (21.5-inch, Late 2015) by using clang 9.1.0 instead of GCC 8.2.0 and using CPUs only. I'm also using cmake 3.13.1 and boost 1.68.0.

Here's what I did to successfully install. 

```bash
# Starting in the leela-zero directory (subpackages already cloned)
mkdir build && cd build
CXX=clang++ CC=clang cmake -DUSE_CPU_ONLY=1 ..
cmake --build .
./tests
```

I was able to successfully compile and test without the CPU flag, but neither autogtp nor Lizzie 0.6 worked. That wasn't surprising because the GPU version has never worked on my Mac. What was surprising was not being able to compile either the CPU or GPU version using GCC. If it would be helpful for me to provide compiler output from compiling with GCC, please let me know.

**Comment by gcp** [comment] 2018-11-29 14:39
For me this is not so surprising as clang is the native macOS compiler and GCC is some homebrew package with the usual compatibility issues. 

I would be surprise that CMake selects gcc instead of clang for compiling, though?

**Comment by sethtroisi** [comment] 2019-02-14 07:50
closing old techsupport issue with no update for 2 months

**Closed by sethtroisi** 2019-02-14 07:50 UTC
Labels: techsupport
