### ISSUE TITLE
Apple deprecating OpenCL

### ISSUE THREAD

**Issue by thalessa** [leela-zero/leela-zero#1517] opened 2018-06-04 20:41 UTC
Very relevant news:

https://developer.apple.com/macos/whats-new/

Deprecation of OpenGL and OpenCL

Apps built using OpenGL and OpenCL will continue to run in macOS 10.14, but these legacy technologies are deprecated in macOS 10.14 ... apps that use OpenCL for computational tasks should now adopt Metal and Metal Performance Shaders.

**Comment by ihavnoid** [comment] 2018-06-04 21:10
This isn't good.  I understand OpenCL is a huge mess, but neither Metal doesn't look like a good alternative since it does not support non-Apple platforms.  Hopefully they will leave it as deprecated rather than remove it for a very long time...

**Comment by bjiyxo** [comment] 2018-06-04 21:42
@ihavnoid Allow me to make a brief digression on multi-GPU tasks on #1026. My friend has a 6x1080Ti (PCI-E 3.0x8 x6) device with dual 2696 v4. When he runs 4x1080Ti lz with your Multi-GPU improvement, it works pretty fine (>=95% each with 24 threads). However, when he runs 6x1080Ti lz with the same condition, it cannot reach the same level (~70% each with 36 threads). Do you know how to improve the GPU usage? BTW, he is willing to let you debug on his device. Contact me at jameshsu20032003@yahoo.com.tw if you are interested in it.

**Comment by ihavnoid** [comment] 2018-06-04 21:56
@biiyxo unfortunately I can't work on any code development for another month since I don't even have a PC now.  I don't have any idea why the current code isn't scaling, though...

Did you try increasing the number of threads furthermore after removing the max thread count restriction?  This will need code recompilation though.

**Comment by ihavnoid** [comment] 2018-06-04 23:29
Back to the original topic... it may be possible that we have to move to vulkan.  Anybody with a better insight...?

**Comment by Marcin1960** [comment] 2018-06-05 07:07
There is another news - Microsoft taking over GitHub

https://blogs.microsoft.com/?p=52553832

**Comment by bjiyxo** [comment] 2018-06-05 07:09
@ihavnoid Can you point out where I can remove the max thread count restriction?

**Comment by gcp** [comment] 2018-06-05 13:27
>it may be possible that we have to move to vulkan.

Apple doesn't support Vulkan.

**Comment by MarcelGruenauer** [comment] 2018-06-05 13:32
Arstechnica: "Vulkan is coming to macOS and iOS, but no thanks to Apple" https://arstechnica.com/gadgets/2018/02/vulkan-is-coming-to-macos-ios-but-no-thanks-to-apple/

**Comment by gcp** [comment] 2018-06-05 13:35
Yeah but that's an emulation/translation layer. Not sure you'd want to use that with Leela or what the performance impact would be.

I certainly wouldn't want to write a Vulkan backend only to have that run through an emulation layer.

**Comment by gcp** [comment] 2018-06-05 13:42
I don't see anything actionable for us. 

OpenCL support is deprecated but not removed. Note that for many people it never worked in the first place because the current OpenCL drivers on macOS don't tend to be very good. CPU support will keep working.

If it does actually get removed at some point, you'll have to look at what the Apple hardware and software stack looks like at that moment. If they don't have any decent GPUs in their hardware, there's no point in bothering. If they're on NVIDIA cards, you can revive the cuDNN/CUDA backend. If someone crazy enough writes one, you can use a Metal Performance Shader backend. Maybe they end up adding an neural network inference API to macOS, in which case you'd certainly want to use that instead. (This isn't as crazy as it seems - macOS ships with native, optimized BLAS support already)

**Comment by ihavnoid** [comment] 2018-06-06 20:59
I wholeheartedly agree with @gcp that we probably shouldn't take any action at least now.  However, it seems that the minimum we can do now is to clean up the code to allow different types of compute backends to coexist.

**Comment by iteachcs** [comment] 2018-06-07 05:04
@bjiyxo 
> Can you point out where I can remove the max thread count restriction?

I am no expert but I think the variable cfg_max_threads in the source code specifies the restriction.  But it seems to be a fairly big number to affect multi-GPU performance.

Anyway, I am also curious of the effectiveness of multi-GPU support of Leela zero.  In my test, an 8-GPU setup is actually slower than a 4-GPU setup.  This might warrant creating a new issue for more insights.

**Comment by bjiyxo** [comment] 2018-06-07 06:43
@iteachcs Your situation is similar to mine. It's hard to confirm whether the problem is related to opencl or other unknown issues.

**Comment by sethtroisi** [comment] 2019-02-14 06:56
closing older issues, no discussion for >6 months

**Closed by sethtroisi** 2019-02-14 06:56 UTC
