### ISSUE TITLE
Leela Zero logs for AI Go Competition

### ISSUE THREAD

**Issue by bood** [leela-zero/leela-zero#1272] opened 2018-04-27 04:52 UTC
I'm asked to upload logs here, so here they are.
FYI: `max_lcb_root` branch of @roy7 + 20b (v11) trained by @bjiyxo is used for the match. Hardware is 6x1080ti.

Match 1, vs Golois
![lz_golois_match1](https://user-images.githubusercontent.com/1168942/39345088-1860f558-4a19-11e8-87d4-dba5546346ec.png)
[lz_golois_match1.sgf.gz](https://github.com/gcp/leela-zero/files/1953860/lz_golois_match1.sgf.gz)
[lz_golois_match1.txt](https://github.com/gcp/leela-zero/files/1953855/lz_golois_match1.txt)

Match 2, vs Dolbram
![lz_stone_match2](https://user-images.githubusercontent.com/1168942/39345090-1910f41c-4a19-11e8-86f3-dec1f2431035.png)
[lz_stone_match2.sgf.gz](https://github.com/gcp/leela-zero/files/1953861/lz_stone_match2.sgf.gz)
[lz_stone_match2.txt](https://github.com/gcp/leela-zero/files/1953856/lz_stone_match2.txt)

Match 3 vs FineArt (Log of first two moves are lost and were manually fixed afterwards)
![lz_fineart_match3](https://user-images.githubusercontent.com/1168942/39358512-df63dcd6-4a48-11e8-94f4-27542cf39b19.png)
[lz_fineart_match3.sgf.gz](https://github.com/gcp/leela-zero/files/1954720/lz_fineart_match3.sgf.gz)
[lz_fineart_match3.txt.gz](https://github.com/gcp/leela-zero/files/1954722/lz_fineart_match3.txt.gz)

Match 4 vs Phoenix
![lz_phoenix_match4](https://user-images.githubusercontent.com/1168942/39354965-71ffed74-4a3e-11e8-87de-2f5f1b17cc37.png)
[lz_phoenix_match4.sgf.gz](https://github.com/gcp/leela-zero/files/1954503/lz_phoenix_match4.sgf.gz)
[lz_phoenix_match4.txt.gz](https://github.com/gcp/leela-zero/files/1954504/lz_phoenix_match4.txt.gz)

Match 5 vs HeroZ
![lz_heroz_match5](https://user-images.githubusercontent.com/1168942/39358659-6adbbbc6-4a49-11e8-9676-9cf8d156b436.png)
[lz_heroz_match5.sgf.gz](https://github.com/gcp/leela-zero/files/1954732/lz_heroz_match5.sgf.gz)
[lz_heroz_match5.txt.gz](https://github.com/gcp/leela-zero/files/1954733/lz_heroz_match5.txt.gz)

Semifinal vs Phoenix
![lz_phoenix_semifinal](https://user-images.githubusercontent.com/1168942/39396410-2d85b894-4b20-11e8-96bf-f77dd0542e8b.png)
[lz_phoenix_semifinal.sgf.gz](https://github.com/gcp/leela-zero/files/1957691/lz_phoenix_semifinal.sgf.gz)
[lz_phoenix_semifinal.txt.gz](https://github.com/gcp/leela-zero/files/1957692/lz_phoenix_semifinal.txt.gz)

Rank 3/4 match vs TS
![lz_ts_34_fixed](https://user-images.githubusercontent.com/1168942/39396404-1e357ae6-4b20-11e8-9b2c-6c95a84182cf.png)
[lz_TS_34_fixed.sgf.gz](https://github.com/gcp/leela-zero/files/1957688/lz_TS_34_fixed.sgf.gz)
[lz_TS_34.txt.gz](https://github.com/gcp/leela-zero/files/1957689/lz_TS_34.txt.gz)

**Comment by l1t1** [comment] 2018-04-27 04:58
could the sgf format express time used, so that human can replay the game as reality

**Comment by bood** [comment] 2018-04-27 05:04
Code to convert the log to sgf is here, you can improve it to include timing:
https://github.com/bood/leela-zero/blob/log2sgf/scripts/log2sgf.py

**Comment by higherdim** [comment] 2018-04-27 05:11
what's the HW used today?  4x TitanV?

**Comment by bood** [comment] 2018-04-27 05:15
6x1080ti

**Comment by hydrogenpi** [comment] 2018-04-27 05:37
![image](https://user-images.githubusercontent.com/35181396/39346327-6794707c-49a2-11e8-9887-2f37c6c639b7.png)

**Comment by gcp** [comment] 2018-04-27 07:33
>max_lcb_root branch of @roy7

I'm curious what test results lead to that conclusion. Tentative testing seemed to indicate that for fixed time the lcb branch did not help: https://github.com/gcp/leela-zero/pull/883#issuecomment-383380871

What's the timecontrol in the tournament?

(I hope @roy7's branch is up to date with bugfixes!)

> 20b (v11) trained by @bjiyxo

I assume this was temporarily withheld in order to avoid preparation from competitors. There is data now that supports the belief that the larger networks "scale" better: https://github.com/gcp/leela-zero/issues/1113#issuecomment-384711402, so this was likely a good choice.

**Comment by 22nsuk** [comment] 2018-04-27 10:08
Match 3 is really strange. Is that true match 3? Other sites have a different order.

**Comment by croosn** [comment] 2018-04-27 10:29
@bood Where can one download 20b v11? Up to which network was it trained on?

**Comment by bood** [comment] 2018-04-27 10:30
> Match 3 is really strange. Is that true match 3? Other sites have a different order.

Apparently I made a mistake when fixing the missing two moves. Should be fixed now.

**Comment by godmoves** [comment] 2018-04-27 10:33
@22nsuk Maybe they  look at the board from different angle. The log comes from the machine used  in the match.

@gcp I find that LZ's multi GPU utilization is quite low, are there any improvements? Someone tests it on a machine with 16 x P100, it seems that when there are more than 6 GPUs the utilization drops quickly.

**Comment by gcp** [comment] 2018-04-27 10:50
>are there any improvements?

No, the last attempt was at best inconclusive: https://github.com/gcp/leela-zero/pull/1026

Almost no-one has such a machine, nearly none of the users and none of the developers, so I would not hope for any changes there.

**Comment by gcp** [comment] 2018-04-27 10:53
A simple thing you could try is to increase VIRTUAL_LOSS_COUNT in UCTNode.h. But you again need testing to see if the program does not become "stronger but weaker".

**Comment by bood** [comment] 2018-04-27 10:59
> No, the last attempt was at best inconclusive: #1026

I was told they tried #1026 on their 6x1080ti machine and the result is promising: first move n/s increased from 3000n/s to about 4500n/s. Could be due to different cards or virtual machines environment, not sure why exactly.

**Comment by roy7** [comment] 2018-04-27 11:38
> I'm curious what test results lead to that conclusion. Tentative testing seemed to indicate that for fixed time the lcb branch did not help

The only test we've seen that hurts (SPRT verified) was on 7.5 minute clock of lcb without timemanage vs next with timemanage. And then we confirmed timemanage on/off alone without lcb sees that sort of drastic result on a short clock. I assume they had timemanage on. As such it seems that lcb can't hurt, only help. Too bad no byoyomi for the AI games though.

@gcp Some of the papers I've read use "root parallelization", which isn't the approach LZ does. That is, each GPU runs its own tree search with its own tree, then at the end of search time the trees are merged and a move is selected. Did you ever consider this for LZ? It'd allow use of many GPUs without any virtual loss tricks. In terms of tree re-use it'd be nice to merge all of the data from all trees of the move selected, but leaving re-use aside for a moment you'd only need to add the visits of the root moves then choose the move with highest visit (given the current selection approach).

> (I hope @roy7's branch is up to date with bugfixes!)

They can pull official /next and just add my branch as a remote and merge the PR to it, but I do try to keep things  up to date by merging /next every time I work on it.

**Comment by bood** [comment] 2018-04-27 11:44
@roy7 Tomorrow's match timing will be 25mins + 5x60s (byoyomi now). I assume best time setting would be `time_settings 0 60 1`? Any better alternatives?

**Comment by gcp** [comment] 2018-04-27 11:48
>Any better alternatives?

 ```kgs-time_settings byoyomi 1500 60 5``` should just work.

**Comment by gcp** [comment] 2018-04-27 12:01
>As such it seems that lcb can't hurt, only help

I don't understand. 

I thought we established that:
a) with fixed visits/only byo yomi time it helps, but the issue is muddled because of #1252, i.e. Leela incorrect exits early in that case.

b) with fixed time it's no better.

This is why it wasn't merged. We are in case (b), so I'm puzzled why it was used. It was already established not to help.

**Comment by gcp** [comment] 2018-04-27 12:16
>Did you ever consider this for LZ?

No, because it's terrible. Completely offtopic for this thread, though.

**Comment by Tsun-hung** [comment] 2018-04-27 12:17
> kgs-time_settings byoyomi 1500 60 5 should just work.

Nope, the time_settings isn't that meaning.I find  specification below:

time_settings: Set time allowance
Arguments: int main_time, int byo_yomi_time, int byo_yomi_stones
Fails:     syntax error
Returns:   nothing
Status:    GTP version 2 standard command.
that mean play 5 moves in 60s, and I have tested the command by time_settings 0 30 5

**Comment by Tsun-hung** [comment] 2018-04-27 12:26
You're right, I'm blind T_T

**Comment by gcp** [comment] 2018-04-27 13:07
>I have tested the command and it runs correctly.

Awesome!

**Comment by roy7** [comment] 2018-04-27 13:36
@gcp It's true that in an absolute clock test 450 seconds didn't show any gain. No test shows lcb is weaker than /next though and many tests show it is stronger. So it seems safe to use. It's also possible it's stronger with higher clocks (untested). 450 seconds is maybe just too little time per move. Although what confuses me there is how strong lcb is with -v 200. Surely a game with -v 200 is faster than 450 seconds?

**Comment by gcp** [comment] 2018-04-27 13:59
>many tests show it is stronger.

Which ones, on absolute time?

**Closed** 2019-02-14 06:23 UTC
