### ISSUE TITLE
Multiple games in parallel (-g) leads to more shorter games on AMD cards?

### ISSUE THREAD

**Issue by bood** [leela-zero/leela-zero#359] opened 2017-12-12 10:15 UTC
It is reported that when using `-g N`, the average game length is somehow shorter than the default `-g 1`.

Run `-g 2` and `-g 3` for an hour on a `Win10 + RX480` machine, `-g 3` has a average game length of `82.3` while `-g 4` has an average game length of `416`

Another report from `Win10 + RX580`, where `-g 2` generates more shorter games than `-g 1`

But the issue is never observed on a Nvidia card yet. Really odd to me since I wouldn't expect separate processes interfere with each other at all.

See doc below for histogram details, I can upload sgf files if needed.

https://docs.google.com/spreadsheets/d/15xqk5ZZ4Yh7gr-7EoeFV0auaQEh3Nkquf7NpnhfX4_A/edit?usp=sharing

EDIT: SGF for RX480 uploaded:
https://drive.google.com/open?id=15IT87bXEPddDUQaXGqvn5QU1lbEL25Lt

EDIT2: SGF with `-debug` data uploaded:
https://drive.google.com/open?id=1HXuaeXvKNjhGzX_iPu1kQJVtVUm08EKz

**Comment by marcocalignano** [comment] 2017-12-12 10:30
This statistic is done over 41 games? I'd like to see a better statistic. 
And if you run -g 1 multiple times? Does the length change too? 
And this should be a problem or an observation?

**Comment by bood** [comment] 2017-12-12 10:38
The data is not from me but other volunteers, I'd like a thousand games too but it's hard. However, existing distribution do look different enough for different `-g` settings already.

Yes, I just asked and even with several `-g 1` instance running at the same time, you see similar situation too.

This is observation for now but could be an potential problem, that's why I summarized data and posted it here. Shouldn't the behavior be the same across all the instances?

**Comment by killerducky** [comment] 2017-12-12 10:45
This is autogtp right? What version are they running? What OS?

Can you ask them to run "autogtp -g 2 --keep savedir --debug savedir" and the same with -g 3. Then upload the sgfs, *txt*, *debug* files? That might show something.

**Comment by bood** [comment] 2017-12-12 10:59
All on autogtp v0.9, windows version

Okay, I can ask them to do this.

**Comment by evanroberts85** [comment] 2017-12-12 11:25
Any game with less than a 100 moves is higly unusual with the current network, let alone the average accross several games. Best to upload a .sgf so we can see what is happening.

**Comment by bood** [comment] 2017-12-12 14:48
Just uploaded sgf files from RX480 (without debug data yet)

https://drive.google.com/open?id=15IT87bXEPddDUQaXGqvn5QU1lbEL25Lt

**Comment by killerducky** [comment] 2017-12-12 17:53
@bood here is an easier way to get debug info, it's probably more informative too:

https://github.com/gcp/leela-zero/issues/361#issuecomment-351130284

**Comment by barrtgt** [comment] 2017-12-12 19:54
After installing the new ATI driver 17.12.1, it is very apparent there is an issue with having the -g parameter set to a higher number. Having the workload in the driver settings set to graphics, a -g 5 or higher will results in very short games all of the time, with about a game length of less than 20 moves. Changing the driver workload to compute having -g 4 or higher will do the same. Previously, with ATI driver 17.4.4, Leela merely stopped functioning.

**Comment by roy7** [comment] 2017-12-12 20:02
My first guess was that if there's too much cpu available and not enough gpy to go around, what happens there with the tree search? If it can only resolve a small # of nodes if the GPU is split multiple ways, that'd affect the resulting game play wouldn't it? Or does the playout count only relate to number of GPU NN nodes resolved, so it won't play any differently it'd only play more slowly?

But apparently this is AMD specific, and people running high # of clients on Nvidia have no difference in game length at all?

**Comment by killerducky** [comment] 2017-12-12 20:03
We need someone who can actually debug the code that has an ATI card. Anyone?

**Comment by marcocalignano** [comment] 2017-12-12 23:55
So it is sel-playing since 153 Minutes it did 9 games and and a average of 320 moves x games. I saw only one game with 15 move I have a Nvidia GTX 760

**Comment by killerducky** [comment] 2017-12-13 00:30
I just found the leelaz --log option... All my googling how to redirect stderr+stdout was not needed.

```
printf "auto" | ./leelaz -w ~/networks/920k.txt -p 10  -r 0  -m 0  -t 1  -d   --noponder  -s 0 -l run1.txt
printf "auto" | ./leelaz -w ~/networks/920k.txt -p 10  -r 0  -m 0  -t 1  -d   --noponder  -s 0 -l run2.txt
```

**Comment by barrtgt** [comment] 2017-12-13 01:15
Since I'm on Windows, I tried print and omitting the "auto" part and in the middle of the output it said: `Leela: ? unknown command`

**Comment by killerducky** [comment] 2017-12-13 01:30
@barrtgt windows version:
`echo auto | leelaz.exe -w networkname -p 10  -r 0  -m 0  -t 1  -d   --noponder  -s 0 -l run1.txt
`


Or probably simpler and platform independent:
`leelaz.exe -w networkname -p 10  -r 0  -m 0  -t 1  -d   --noponder  -s 0 -l run1.txt
`
And at the prompt
`Leela: auto
`

**Comment by bood** [comment] 2017-12-13 01:47
@barrtgt Are you saying leelaz can not run with the old ATI driver at all? or leelaz does not have this problem with old ATI driver?

**Comment by barrtgt** [comment] 2017-12-13 01:49
I had Leela on auto with the command from above during the period it ended the game early. Maybe someone could interpret this. I'm headed out for the night. [URL=http://m.uploadedit.com/bbtc/1513129699790.txt][IMG] http://m.uploadedit.com/bbtc/1513129699790.gif [/IMG][/URL]

**Comment by killerducky** [comment] 2017-12-13 02:17
@barrtgt Thanks for the debug file. I don't see anything obviously wrong right away, the game lasted 356 moves. White does pass early a few times, like move 22. That's probably because there are only 10 playouts so the search didn't see it's bad yet. Can you try the same command with -p 1600 instead of -p 10?

**Comment by bood** [comment] 2017-12-13 02:36
@killerducky Is `-debug` option enough for data collection too? I think those command is more complicated than just running `autogtp` with `-debug`. I'll ask the reporters to try with `-debug` if it is enough.

**Comment by killerducky** [comment] 2017-12-13 02:42
Either way is ok.

**Comment by bood** [comment] 2017-12-13 05:16
@killerducky Here is it:
https://drive.google.com/open?id=1HXuaeXvKNjhGzX_iPu1kQJVtVUm08EKz

**Comment by bood** [comment] 2017-12-13 06:40
Short games are all ended by a double pass started by BLACK.
By looking into the debug data, it seems that BLACK:pass has a unreasonable high probability when it played:
e.g.  49.7% in game `f79b658c143244dfaa86671a5118f998`, 39.68% in game `a8a39270ecd24a80bae80117a62e2ce4`

**Comment by jkiliani** [comment] 2017-12-13 13:10
Commenting here since this appears to apply in my case as well. I just had 4 self-play games done with autogtp (4 white wins of game length 48-74 moves), this time with both game and training data as well as the debug file saved. If @killerducky is interested, here are the files:

Game 1 (sgf, training data, debug file):
https://drive.google.com/open?id=1KU05LvHAurUasp9d5nKahXS4UMd1Nddl
https://drive.google.com/open?id=1gKTu_l9kibaL8Xc46GQyP6zenNm2hDTB
https://drive.google.com/open?id=1yKKXiyXJNCRfX0llJOojTyaIr2EuGosp

Game 2:
https://drive.google.com/open?id=1s3_VWNnFoWAwaWGIIWk1YUGhtZe361Vz
https://drive.google.com/open?id=1JZL3XWBkY7AvH2fWcVoiG3ewandNOZEf
https://drive.google.com/open?id=14BJ7-3i7CGJ0i324hOAn-Pi4AsBWWcw_

Game 3:
https://drive.google.com/open?id=19Mn2tbBAtBHlY1JVoFimAyaEe03Watpv
https://drive.google.com/open?id=1zJ2MujnQPCVMt-_2kV-vmqdB7DNiMTe3
https://drive.google.com/open?id=1zaoZH-a2sBf5mXlmSR_as-nyRSbrxCrA

Game 4:
https://drive.google.com/open?id=1wu4k0Ohs0Pne1vdhhXw_tw96b6E4_oWD
https://drive.google.com/open?id=1YBxmHzbmGeM0XeZZMG7zXnCZLSa2HmKO
https://drive.google.com/open?id=1bKYu9cXLK7TVV_k8p0KejaP8hahmjWqD

For reference, I use an Intel Iris integrated GPU. Looks like whatever is happening with AMD also applies to Intel.

**Comment by killerducky** [comment] 2017-12-13 14:58
I took a quick look at bood's f79b658c143244dfaa86671a5118f998.txt.debug.0.gz, there is definitely something wrong, but I don't know what is causing it. Here are the first two lines:
```
1
1 0.646857 0.749762 339
```

The first line is just a revision number. From there on the numbers are: 
```
        out << step.net_winrate
            << " " << step.root_uct_winrate
            << " " << step.child_uct_winrate
            << " " << step.bestmove_visits << std::endl;
```

The first one "net_winrate" should be the same number as when you run the "heatmap" command, at the bottom there is "winrate: 0.697635". But according to this debug, the winrate for an empty board is 1.0!

@bood can you have them try this at the same time autogtp is running:
`leelaz.exe -w networkname -p 10 -r 0 -m 0 -t 1 -d --noponder -s 0 -l heatmap.txt
`
And at the Leela: prompt:
```
heatmap 0
heatmap 1
heatmap 2
heatmap 3
heatmap 4
heatmap 5
heatmap 6
heatmap 7
quit

```

**Comment by killerducky** [comment] 2017-12-13 15:17
I wasn't able to get \n to work in windows. For linux you have to use print, not echo, to get \n to work.

**Comment by bood** [comment] 2017-12-13 15:21
ok, it's said something like `echo,` can do.
so maybe `echo heatmap 0 && echo, && echo heatmap 1 && echo`
Anyway, that guy was not there now, have to wait another 8 to 10 hours.

**Comment by killerducky** [comment] 2017-12-13 15:27
@jkiliani your debug files show the same problem. Can you try the same heatmap commands?

**Comment by bood** [comment] 2017-12-13 15:34
btw, is this 100% win-rate thing somehow related to the high resign probability I saw earlier?

**Comment by jkiliani** [comment] 2017-12-13 15:39
[heatmap.txt](https://github.com/gcp/leela-zero/files/1556044/heatmap.txt)

@killerducky Not sure if this is actually what you need... if not, can you describe more how to get the (multiple?) heat maps you're looking for?

**Comment by killerducky** [comment] 2017-12-13 15:55
Looks like it only did one. I think the \n isn't working, try just running each heatmap N command by itself. BTW these should all be identical since rotating an empty board doesn't do anything but maybe there is a bug in the rotation code.

Your first heatmap shows winrate 0.739108 which is normal. Are you running autogtp at the same time in case the issue is related to GPU load?

**Comment by jkiliani** [comment] 2017-12-13 16:11
I think I got the file you're looking for now, by manually calling leelaz and requesting the different heat maps. Is it correct that they're supposed to show rotations/reflections?

[heatmap.txt](https://github.com/gcp/leela-zero/files/1556189/heatmap.txt)

**Comment by killerducky** [comment] 2017-12-13 16:25
Ok we're getting closer. Yes they are rotations/reflections but since the board is empty they should be identical. On my machine all those heatmap N commands return identical output. But on yours you can see they are different. heatmap 0, 1, 2 look the same but heatmap 3 and 4 have winrate almost 1.0, and have a bunch of 0s in the board layout.

There is a #ifdef USE_OPENCL here, but it's my understanding all clients must have that define on?
https://github.com/gcp/leela-zero/blob/master/src/Network.cpp#L426

I don't see anything obviously wrong in this function
https://github.com/gcp/leela-zero/blob/master/src/Network.cpp#L570

**Comment by jkiliani** [comment] 2017-12-13 16:28
This may interest you as well: 
[heatmap2.txt](https://github.com/gcp/leela-zero/files/1556238/heatmap2.txt)

That's with the supervised network. All heat maps except 1 are OK, heatmap 5 is crap.

**Comment by marcocalignano** [comment] 2017-12-13 17:17
We are compiling our leelaz with the option -ffast-math. I think this makes the games not reproducible.
> -ffast-math
> This option allows GCC to violate some ANSI or IEEE rules and/or specifications in the interest of optimizing code for speed. For example, it allows the compiler to assume arguments to the sqrt function are non-negative numbers and that no floating-point values are NaNs.
> This option should never be turned on by any `-O' option since it can result in incorrect output for programs which depend on an exact implementation of IEEE or ANSI rules/specifications for math functions.
> 
>

**Comment by odeint** [comment] 2017-12-13 17:23
It would still be weird if -ffast-math introduced more than rounding errors, no? We're not comparing hashes here, but actual winrates and heatmaps, and they're _nothing_ like each other, not just some differences at the Nth digit.

**Comment by killerducky** [comment] 2017-12-13 17:50
@sethtroisi do you have any ideas about this? Maybe there is a race condition or some other bug in OpenCL.cpp

**Comment by killerducky** [comment] 2017-12-13 19:18
@roy7 it should be possible to filter the database for this issue. In the training text files line 18 (the training target for the first move), count how many zeros there are. With the current network there shouldn't be more than a very small number. In one of the buggy cases I looked at there were 98 zeros. This will only catch cases where the bug happens on the first move, so after finding these it might be a good idea to also filter all games from that IP until the bug is fixed.

It looks like the training data on https://sjeng.org/zero is not being updated, so I can't try to analyze this myself. I think OGS is hosting it now? I couldn't find the link, anyone have it?

**Comment by jkiliani** [comment] 2017-12-13 19:35
I had this nagging feeling for a while that self-play games by other people that I saw relayed through KGS were of higher quality somehow than those I produced myself... I guess filtering the training data as suggested by @killerducky may work to clean up the database from corrupted games, or at least filter them for future training purposes.

A stop-gap solution might be to implement a change in the leelaz network initialisation at startup. If the client evaluated a batch of 100 or more empty board heatmaps and then compared if they were binary equal, and refused to start or at least to connect to autogtp if they weren't, this would catch any more clients with the same problem as I have on my machine.

**Comment by sethtroisi** [comment] 2017-12-13 22:16
echo -e always you to print newlines

**Comment by gcp** [comment] 2017-12-13 23:53
>My first guess was that if there's too much cpu available and not enough gpy to go around, what happens there with the tree search?

Doesn't matter at all, in the single-thread case the calls are all synchronous.

**Comment by barrtgt** [comment] 2017-12-15 12:01
With the new driver, Leelaz is capable of doing 400ms/g if I run 5 simultaniously, up from the 1400ms/g I am doing currently. So if this issue is ever addressed, it could be fairly significant depending how many people are in the same boat.

**Comment by barrtgt** [comment] 2017-12-15 21:49
Not sure if it means anything, but after I was running some matches on Sabaki, a game between two Leelaz ended with passes with black winning on territory with 95% evaluation passed, and white passes afterward with a 95% evaluation for it. I later loaded the game into GoGui and after checking the positions where both passed, black had 95% and white had 5% for those moves.

**Comment by Dorus** [comment] 2017-12-15 21:53
Please notice Sabaki is notorious for these kind of situations. Especially when you load a game it input the board in the wrong order (it just go line by line), so move order is wrong and that greatly confuses the network.

**Comment by barrtgt** [comment] 2017-12-15 22:05
Oh, I wasn't aware of this. Guess the only proper way to test with autogtp is to use Linux.

**Comment by bood** [comment] 2017-12-16 16:46
@gcp It is reported by a user that the issue seem to be resolved by removing the `opencl.dll` included in the release package. By doing this, program will be using driver's dll instead.

So maybe you need to double check the `opencl.dll` version included in the release package. Maybe the one included in the package is buggy and not up to date.

**Comment by barrtgt** [comment] 2017-12-16 22:29
I updated my benchmark with results with the new driver. The driver behaved differently when a restart is made after changing workloads. Compute workload should be avoided for now.

**Comment by barrtgt** [comment] 2017-12-18 13:50
Finally tested this more extensively:
-g 2:105KB 46 files	2.28KB/file	0 1KB files 0.00%
-g 4:166KB 88 files	1.88KB/file	18 1KB files 20.45%
Only 1 of the 1KB files was a resign. New networks come out faster than I can get data. Looks like I am stuck with -g 2 again.

**Comment by bood** [comment] 2017-12-18 14:01
Have you tried with the opencl.dll of the ATI driver instead of the one in
the release package?

**Comment by gcp** [comment] 2017-12-18 14:03
OpenCL.dll doesn't contain any functionality, it just forwards commands to the different OpenCL drivers that are installed on a system.

**Comment by isty2e** [comment] 2017-12-19 07:24
But it would be safer to double check if the opencl.dll thing is reproducible. Sometimes there are things that don't make sense at all at the first glance but actually happening, so better to be safe.

**Comment by sethtroisi** [comment] 2019-02-14 05:30
Over a year old, closing out

**Closed by sethtroisi** 2019-02-14 05:30 UTC
