### ISSUE TITLE
weird self-atari move by LeeloZero

### ISSUE THREAD

**Issue by pw31** [leela-zero/leela-zero#936] opened 2018-02-26 13:45 UTC
You might want to look at OGS game https://online-go.com/game/11826994.
Last move by W (RoyalZero) puts large own group into self-atari,
bringing winning probabilty from 99.6% down to 0.2%, after which
Leela Zero resigns.

Weird.

**Comment by pheasant75** [comment] 2018-02-26 15:09
@pw31 according to this thread #540, they believe that is fixable by new network weight (neural network should learn how to deal with it).  Although I still wondering why the tree search can't found the obvious self-atari and to avoid it.

**Comment by Cabu** [comment] 2018-02-26 15:11
Not the first time I see such blunder :( But it get better with time :)

**Comment by Cabu** [comment] 2018-02-26 15:12
@pheasant75 I think this is because Leela has still some times a problem counting liberties. But it is a wild guess....

**Comment by roy7** [comment] 2018-02-26 16:26
Here's the full game log. 

http://termbin.com/29j1

**Comment by pheasant75** [comment] 2018-02-26 16:43
It never consider black can play M13.
I am wondering if it is because black can't plan M13 until after white
played G19?  So maybe the M13 was never considered as a black move and the
tree was reused despite the white's hypothetical G19 makes it legal move
for black?


Also, what if black plays G19 instead of R19 in previous move.  Does that
make white sees the M13?

**Comment by roy7** [comment] 2018-02-26 16:46
The heatmap for M13 is '1' if I load it into LZ and poke around. So there just wasn't enough search to realize that's a game losing move I guess. If I load into that move and ask black to move with 500 visits, it never looks at it once.

```
  N8 ->     112 (V:  0.44%) (N: 20.52%) [ 0.00%] [ 0.00%, 6.56%] [ 5.98%] PV: N8 N11 M8 Q5 L3 G5 G4 M13 L7
 C19 ->      50 (V:  0.25%) (N:  9.75%) [ 0.00%] [ 0.00%,14.10%] [12.90%] PV: C19 M13 N8 N11 M8 Q5 L3 G5 G4
  M8 ->      48 (V:  0.47%) (N:  8.84%) [ 0.00%] [ 0.00%,14.65%] [13.40%] PV: M8 N11 N8 Q5 L3 G5 G4 M13 L7
 F15 ->      47 (V:  0.19%) (N:  9.36%) [ 0.00%] [ 0.00%,14.93%] [13.67%] PV: F15 M13 E15 Q5 N8 N11
  Q5 ->      36 (V:  0.55%) (N:  6.32%) [ 0.00%] [ 0.00%,19.03%] [17.46%] PV: Q5 M13 N8 N11 M8 L3 G4 G5 L7 Q2
 E19 ->      31 (V:  0.21%) (N:  6.24%) [ 0.00%] [ 0.00%,21.74%] [19.97%] PV: E19 M13 M8 Q5 N8 N11
  L7 ->      17 (V:  0.38%) (N:  3.22%) [ 0.00%] [ 0.00%,36.05%] [33.39%] PV: L7 Q5 N8 N11 M8 L3
 A14 ->      16 (V:  0.18%) (N:  3.34%) [ 0.00%] [ 0.00%,37.82%] [35.06%] PV: A14 M13 N8 N11 M8
  C4 ->      15 (V:  0.43%) (N:  2.87%) [ 0.00%] [ 0.00%,39.75%] [36.90%] PV: C4 B4 D3 D2 N8 N11 M8 Q5 L3 G5
 N11 ->      14 (V:  0.37%) (N:  2.68%) [ 0.00%] [ 0.00%,41.90%] [38.95%] PV: N11 N12 N8 N11 M8 Q5 L3 M13
 G15 ->      13 (V:  0.43%) (N:  2.55%) [ 0.00%] [ 0.00%,44.27%] [41.22%] PV: G15 M13 N8 N11 M8
 G14 ->      13 (V:  0.40%) (N:  2.47%) [ 0.00%] [ 0.00%,44.27%] [41.22%] PV: G14 M13 F15 Q5 N8
  G5 ->      10 (V:  0.40%) (N:  1.96%) [ 0.00%] [ 0.00%,53.24%] [49.88%] PV: G5 G4 N8 N11 M8
  G4 ->       9 (V:  0.36%) (N:  1.68%) [ 0.00%] [ 0.00%,57.02%] [53.58%] PV: G4 M13 N8 N11 M8 Q5
  L3 ->       8 (V:  0.29%) (N:  1.59%) [ 0.00%] [ 0.00%,61.33%] [57.83%] PV: L3 M13 N8 N11 M8
440 visits, 44214 nodes, 439 playouts, 2743 n/s
```

**Comment by Eddh** [comment] 2018-02-26 16:54
It's a bit worrying that it hasn't learned that by now though. More than 4 millions games. Is it really because we only have 6 blocks ? This seems like a relatively small group to me.
I guess we'll never know until we go for more blocks.

**Comment by pheasant75** [comment] 2018-02-26 17:02
True.  Probably most of the time it learns is that it is a suicide move.
So NN probability is really low.
And your test reveals that both side of the self-play LZ will not able to
find this move in the playout setting we have.  So make it more difficult
to learn.

**Comment by WhiteHalmos** [comment] 2018-02-26 17:21
@Eddh would a 0.0 minimum have helped in this case?

**Comment by Eddh** [comment] 2018-02-26 17:29
It would have searched the miracle bad policy move sooner probably. But well I've already managed to make a lot of modifications to fpu which works for specific cases like ladder but that aren't making an  improvement in terms of general winrate so what to do ? I just want to let deepmind do their NN managed tree search at that point.

Edit : I guess there might be a noticeable improvement to winrate if I tested against AI that know ladders. But that would be leaving the "zero" approach right ?

**Comment by ThomasCabaret** [comment] 2018-02-26 22:13
Maybe the approach suffers of some topological issues, I mean, as it is designed alphago cannot learn to count liberties, he can only learn to count liberties location by location. He can be really good at doing so in most of the area on the board but bad a some. I think we can more or less test this hypothesis, by shifting or reflecting the above shape and see how it deals with it. It might also explain something else I saw in another thread: why average of 2 networks can lead to a significantly stronger network, maybe because this way it can get rid of topological holes in the concepts computation.  Just a guess.

**Comment by wctgit** [comment] 2018-02-26 23:15
This could be an example of how fpu reduction during _training_ might be making it harder to learn certain kinds of moves and concepts. But again, this is just a hunch and I don't have a definitive opinion on this yet. Needs more testing, IMO.

**Comment by Eddh** [comment] 2018-02-26 23:32
Probably not about fpu reduction during training no since I've tried using older nets and they also miss this move. Example with 6665 : 
```
Passes: 0            Black (X) Prisoners: 7
Black (X) to move    White (O) Prisoners: 10

   a b c d e f g h j k l m n o p q r s t
19 . . . X . X(O)O X X . . . . . X X O O 19
18 . . X O X X O O O X X . . . . . X X O 18
17 . X X O X X X O O O X X X . X X O O O 17
16 X . X O O O X X X O O O X . . X X X O 16
15 . X O O . . . X O O O X X . X X O O O 15
14 . O X X O O . X X X O O X X O X O . . 14
13 . X X . X O X X X O X . O O O O . O . 13
12 . . X . X O O X O O O O . . O . O . . 12
11 X . . X X X X O X X X O . O . O . . . 11
10 O X X X O O O O O X X X O X O O . . . 10
 9 O X O X O X X O X . X O O X O X O . .  9
 8 O O O O O O X X X X X . . X O X O . .  8
 7 O . O . O O O X X O . X X X X X O . .  7
 6 . O O O O X O O X O X O O X . X X O .  6
 5 . . O X X X . O X X O O O X X . O O .  5
 4 . . . O X X . O O O O O X X O O . X .  4
 3 . . O . O X X O X X . O O O O X O . .  3
 2 . . . . O O X X . X X X O . . . . . .  2
 1 . . . . . O O X X . . X X O . . . . .  1
   a b c d e f g h j k l m n o p q r s t

Hash: 4B900E606B20979E Ko-Hash: A4F2AA135EEB09B6

Black time: 01:00:00
White time: 01:00:00

Leela: genmove B
Thinking at most 50.0 seconds...
NN eval=0.000869
Playouts: 1342, Win:  1.07%, PV: N8 N11 M8 Q5 L7 L3 G4 G5 B11 M13 A14
Playouts: 3136, Win:  0.94%, PV: N8 N11 M8 Q5 L7 L3 G4 G5 B11 M13 A14 B2 F15
Stopping early.

  N8 ->     756 (V:  0.82%) (N: 15.89%) PV: N8 N11 M8 Q5 L7 L3 G4 G5 F15 M13 E15 Q2 G14
  Q5 ->     501 (V:  1.48%) (N:  4.49%) PV: Q5 M13 N8 N11 M8 L3 G4 G5 L7
  M8 ->     489 (V:  1.06%) (N:  8.15%) PV: M8 N11 N8 Q5 L7 L3 G4 G5 B11 M13 A14
  L7 ->     467 (V:  0.87%) (N:  9.34%) PV: L7 Q5 N8 N11 M8 L3 G4 G5 B11 M13 A14
  L3 ->     334 (V:  0.98%) (N:  6.09%) PV: L3 Q5 N8 N11 M8 G4 G5 M13 L7
  D3 ->     290 (V:  1.69%) (N:  1.46%) PV: D3 D2 C4 B4 N8 N11 M8 Q5 L7 L3
 F15 ->     245 (V:  0.52%) (N:  6.49%) PV: F15 Q5 N8 N11 M8 L3 G4 G5
 G15 ->     176 (V:  0.81%) (N:  3.71%) PV: G15 M13 N8 N11 M8 Q5 L3 G5
 E19 ->     172 (V:  0.66%) (N:  4.12%) PV: E19 Q5 N8 N11 M8 L3 L7 G5 G4
 C19 ->     169 (V:  0.60%) (N:  4.24%) PV: C19 M13 L7 Q5 N8 N11 M8 L3
  G4 ->     153 (V:  1.07%) (N:  2.54%) PV: G4 G5 N8 N11 M8 Q5 L3 M13 L7
 N11 ->     153 (V:  1.04%) (N:  2.61%) PV: N11 N12 N8 N11 M8 Q5 L7 L3 G4 G5
  G5 ->     143 (V:  0.96%) (N:  2.64%) PV: G5 G4 L7 Q5 L3 N8
 B11 ->      94 (V:  0.78%) (N:  2.03%) PV: B11 M13 N8 N11 M8 L3 G4
 G14 ->      79 (V:  0.78%) (N:  1.73%) PV: G14 M13 N8 N11 M8 Q5 L7 L3
 E15 ->      65 (V:  0.96%) (N:  1.21%) PV: E15 Q5 N8 N11 M8 L3 L7 G5
  P1 ->      64 (V:  1.32%) (N:  0.74%) PV: P1 O2 N8 N11 M8 Q5 L7 L3
  C4 ->      64 (V:  0.98%) (N:  1.17%) PV: C4 B4 D3 D2 N8 N11 M8 Q5 L7
 A14 ->      60 (V:  0.69%) (N:  1.41%) PV: A14 M13 N8 N11 M8 Q5 L7
  O2 ->      41 (V:  1.05%) (N:  0.70%) PV: O2 P2 P1 Q1 N8 N11 M8
 A18 ->      35 (V:  0.78%) (N:  0.75%) PV: A18 M13 N8 N11 M8 Q5
 B19 ->      34 (V:  0.83%) (N:  0.72%) PV: B19 Q5 N8 N11 M8
 B12 ->      28 (V:  0.85%) (N:  0.58%) PV: B12 M13 N8 N11 M8 Q5
 D12 ->      26 (V:  0.88%) (N:  0.53%) PV: D12 Q5 N8 N11 M8
 D13 ->      26 (V:  0.79%) (N:  0.55%) PV: D13 M13 N8 N11 M8 Q5
 C11 ->      23 (V:  0.78%) (N:  0.52%) PV: C11 M13 N8 N11 M8 Q5
 P18 ->      21 (V:  0.71%) (N:  0.50%) PV: P18 Q5 N8 N11 M8 L3 G4
 B16 ->      20 (V:  0.69%) (N:  0.48%) PV: B16 M13 N8 N11 M8 Q5
 A13 ->      20 (V:  0.68%) (N:  0.48%) PV: A13 Q5 N8 N11 M8 L3
4749 visits, 474233 nodes, 4748 playouts, 633 n/s

Eval (0.82%) looks bad. Resigning.
= resign
```

**Comment by roy7** [comment] 2018-02-26 23:50
A thought could be that any move with a heatmap over 1 should get at least 1 visit before we descend the tree further. That might be terrible with random networks (super wide shallow trees) though. But then, those networks won't learn until the value network has some slight idea how to move towards wining anyway.

Or maybe not. Even this late game board position has 77 moves with >=1 on the heatmap. Too much branching factor to try and evaluate all of them once before searching.

**Comment by roy7** [comment] 2018-02-26 23:53
We might have to accept LZ just hasn't learned enough to play this position correctly, even though a new player knows to capture a 16 stone group. ;)

**Comment by Eddh** [comment] 2018-02-27 00:17
> A thought could be that any move with a heatmap over 1 should get at least 1 visit before we descend the tree further.

You mean at root level? That would be impossible to do everywhere. But I'm considering, maybe for training at least, exploring every non zero root move is good. But we can't know for sure unless we do tests like alderi toki on 9x9.

**Comment by roy7** [comment] 2018-02-27 01:02
A thought for training to locate these things, it'd make games slower of course, but consider if we did an NN eval on every move that makes a capture on every turn. (Every move that leads to atari might be way too many moves, I'm not sure.) Normal captures that are bad moves or wastes of time will have low % of the MCTS playouts as normal, and so not really change training. But when you find those moves that are important and weren't in the heatmap, a lot of remaining search will pour into it, which will change the training targets that it needs to learn this specific capture was very important whereas other captures were not.

**Comment by roy7** [comment] 2018-02-27 01:14
Huh was just looking at start of game heat maps in 9ac6. I had idea it had gotten so sharp. There's only 12 candidate moves to start the game. And after a 4-4 move, there's only 10 candidate responses.

**Comment by Splee99** [comment] 2018-02-27 04:07
It doesn't take that many playouts for LZ to find M13 after G19 is played. I think LZ understands the liberty issue. However, the problem is that LZ didn't know M13 was the answer to G19 even after 128339 playouts in my test with the latest weights.

**Comment by Splee99** [comment] 2018-02-27 04:31
Without white G19, black M13 is a suicide move and by definition is illegal. After G19 is played by white, the M13 IS legal for black. So I'm not sure when building the search tree, if the previous move is considered while checking whether a new move is legal. I'm trying to read the code, but I'm really not so familiar with it.

**Comment by killerducky** [comment] 2018-02-27 04:36
Here is what I get for Black finding M13 after White Blunders G19. After 1793 playouts it thinks Black is losing. At 3353 it has found M13, but still thinks it is losing. By 5180 it is starting to realize it will win.
```
>>genmove b    
Thinking at most 50.0 seconds...
NN eval=0.001063
Playouts: 1793, Win:  0.39%, PV: N8 N11 M8 Q5 L3 G5 G4 M13 L7 B2
Playouts: 3353, Win: 37.75%, PV: M13 L14 M14 N11 Q5 M8 L7 G5 G4 L3
Playouts: 5180, Win: 59.58%, PV: M13 L14 M14 N11 Q5 M8 L7 G5 N8 G4 L3
```

So backing up to the previous move. It only takes 11235 playouts before it G19 is no longer the PV, not bad IMO.
```
>>genmove w
Thinking at most 50.0 seconds...
NN eval=0.992339
Playouts: 1968, Win: 99.52%, PV: G19 N8 N11 M8 Q5 L3 G5 G4 M13 L7
Playouts: 4695, Win: 99.46%, PV: G19 N8 N11 M8 Q5 L3 G5 G4 M13 L7 B2 F15
Playouts: 7749, Win: 99.34%, PV: G19 N8 N11 M8 Q5 L3 G5 G4 M13 L7 B2 F15
Playouts: 11235, Win: 99.27%, PV: M13 G19 Q5 N8 N11 M8 L3 L7 G5 G4 Q2 F15 S2
Playouts: 15189, Win: 99.27%, PV: M13 G19 Q5 N8 N11 M8 L3 L7 G5 G4 Q2 F15 S2
Playouts: 19206, Win: 99.29%, PV: M13 G19 Q5 N8 N11 M8 L3 L7 G5 G4 Q2 F15 S2
Playouts: 23731, Win: 99.30%, PV: M13 G19 Q5 N8 N11 M8 L3 L7 G5 G4 Q2 F15 S2
Playouts: 28537, Win: 99.32%, PV: M13 G19 Q5 N8 N11 M8 L3 L7 G5 G4 Q2 F15 S2
Playouts: 33049, Win: 99.33%, PV: M13 G19 Q5 N8 N11 M8 L3 L7 G5 G4 Q2 F15 S2
```

Ok but what does the debug output look like? Why did it quit playing G19? You can see below the PV for G19 still includes black answering with N8. But it only put 2136 playouts. What's going on is that it's already found Black's M13 answer, which is lowering the score of White's G19 move already. If it searched G19 more it would eventually promote the N8 answer into the PV display below. But it will take a very very long time for that because the search is already biased heavily against G19 and into the other moves that are still good.

```
 M13 ->    8956 (V: 99.42%) (N: 17.15%) PV: M13 G19 Q5 N8 N11 M8 L3 L7 G5 G4 B2 F15 Q2 E15
  Q5 ->    6563 (V: 99.44%) (N: 11.47%) PV: Q5 G19 M13 N8 N11 M8 L3 L7 G5 G4 B2 F15 Q2 E15
  M8 ->    4575 (V: 99.44%) (N:  8.31%) PV: M8 L7 G19 N8 N11 Q5 L3 G4 G5 F15 M13 G14 Q2
  G4 ->    3411 (V: 99.54%) (N:  3.90%) PV: G4 G5 G19 N8 N11 M8 L3 Q5 M13 L7 Q2 F15
  G5 ->    2960 (V: 99.53%) (N:  3.52%) PV: G5 G19 M13 N8 N11 M8 G4 Q5 L3 L7 B2 F15
 N11 ->    2590 (V: 99.54%) (N:  2.93%) PV: N11 G19 M13 M8 N8 Q5 L3 G4 G5 L7 R4
  L3 ->    2541 (V: 99.51%) (N:  3.50%) PV: L3 G19 M13 N8 N11 M8 Q5 L7 G5 G4 Q2 F15 S2
 G19 ->    2136 (V: 97.79%) (N: 26.14%) PV: G19 N8 N11 M8 Q5 L3 G5 G4 M13 L7 B2 F15
  L7 ->    1534 (V: 99.29%) (N:  4.21%) PV: L7 L6 G19 M8 N11 N8 Q5 L3 G5 G4 M13
```

So I don't see any real bugs, just NN takes some time to see these issues. @Splee99 can you post logs of your 100,000 move search? Because for me it's working ok. Maybe a different random seed would be different though.

**Comment by Splee99** [comment] 2018-02-27 04:48
OK, I did another test by filling up all the dames manually except G19, then attaching LZ. Here is the log.
```text
Leelaz-latest> play B F18
= 
? Leelaz-latest> play W T19
= 
? Leelaz-latest> play B R19
= 
? Leelaz-latest> play W N11
= 
? Leelaz-latest> play B M8
= 
? Leelaz-latest> play W N8
= 
? Leelaz-latest> play B Q5
= 
? Leelaz-latest> play W L3
= 
? Leelaz-latest> play B G4
= 
? Leelaz-latest> play W G5
= 
? Leelaz-latest> play B E19
= 
RNG seed: 6751232037650963633
Detecting residual layers...v1...128 channels...6 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.1.83
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 1050
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 388.19
Device speed:  1455 MHz
Device cores:  5 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1050
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
BLAS Core: Barcelona
? Leelaz-latest> genmove W
= G19
Thinking at most 59.0 seconds...
NN eval=0.992177
Playouts: 1812, Win: 99.60%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2
Playouts: 4278, Win: 99.69%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2
Playouts: 7036, Win: 99.72%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2
Playouts: 10111, Win: 99.74%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14
Playouts: 13449, Win: 99.75%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14
Playouts: 17162, Win: 99.76%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14
Playouts: 20531, Win: 99.76%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14
Playouts: 23919, Win: 99.76%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14
Playouts: 27155, Win: 99.76%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14
Playouts: 30532, Win: 99.76%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14 R4
Playouts: 34052, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14 R4
Playouts: 37718, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14 S3
Playouts: 41126, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14 R4
Playouts: 44120, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14 S3 pass
Playouts: 47616, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14 R4
Playouts: 50438, Win: 99.76%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14 R4
Playouts: 53882, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14 R4
Playouts: 56877, Win: 99.76%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14 S3 pass
Playouts: 60066, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14 S3 pass
Playouts: 62980, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14 S3 pass
Playouts: 66070, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14 S3 pass
Playouts: 69126, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 R4 L7 Q2 A14 S3 pass
Playouts: 72326, Win: 99.77%, PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14 R4
 G19 ->   46301 (V: 99.84%) (N: 46.02%) PV: G19 F15 M13 E15 B2 G14 Q2 L7 S2 A14 R4
 M13 ->    8584 (V: 99.69%) (N: 14.42%) PV: M13 G19 B2 L7 Q2 F15 pass E15 pass
  B2 ->    2216 (V: 99.66%) (N:  4.00%) PV: B2 G19 M13 L7 Q2 F15 pass E15 pass
  R4 ->    1819 (V: 99.67%) (N:  3.21%) PV: R4 G19 M13 L7 Q2 A14 S2 F15 T4 E15
  Q2 ->    1752 (V: 99.66%) (N:  3.15%) PV: Q2 G19 M13 L7 S2 A14 pass F15 S10 E15 T4
  S3 ->    1056 (V: 99.68%) (N:  1.84%) PV: S3 G19 M13 L7 Q2 F15 T4 E15 R4 G14
 S10 ->    1044 (V: 99.68%) (N:  1.80%) PV: S10 G19 M13 L7 Q2 A14 S2 F15 T4
  S2 ->     786 (V: 99.66%) (N:  1.42%) PV: S2 G19 M13 L7 Q2 A14 pass F15 S10 E15 T4
  S7 ->     784 (V: 99.61%) (N:  1.59%) PV: S7 G19 M13 L7 Q2 F15 S2 E15 pass G14
  P2 ->     741 (V: 99.66%) (N:  1.35%) PV: P2 G19 M13 L7 R4 F15 Q2 E15 S3
pass ->     706 (V: 99.65%) (N:  1.32%) PV: pass G19 M13 L7 Q2 F15 S2 E15 R4
  D2 ->     664 (V: 99.63%) (N:  1.29%) PV: D2 G19 M13 L7 Q2 F15 S2 E15 pass
  C2 ->     622 (V: 99.65%) (N:  1.15%) PV: C2 G19 M13 L7 Q2 F15 S2 E15 pass
  S8 ->     598 (V: 99.67%) (N:  1.06%) PV: S8 G19 M13 F15 R4 E15 Q2 G14 S2
  K1 ->     551 (V: 99.50%) (N:  1.40%) PV: K1 L1 G19 L7 M13 F15 B2 E15 R4 G14
  D3 ->     477 (V: 99.63%) (N:  0.93%) PV: D3 G19 M13 L7 R4 F15 Q2 E15 pass G14
  B3 ->     394 (V: 99.64%) (N:  0.74%) PV: B3 G19 M13 L7 Q2 F15 S2 E15 pass
  C4 ->     378 (V: 99.63%) (N:  0.73%) PV: C4 G19 M13 L7 B2 A14 Q2 F15 pass
 R10 ->     366 (V: 99.68%) (N:  0.63%) PV: R10 G19 M13 L7 Q2 F15 S2 E15 R4
  O2 ->     357 (V: 99.66%) (N:  0.65%) PV: O2 G19 M13 L7 Q2 F15 S2 E15 R4
  L7 ->     343 (V: 99.58%) (N:  0.75%) PV: L7 L6 G19 F15 M13 E15 B2 G14 Q2
  S9 ->     293 (V: 99.68%) (N:  0.50%) PV: S9 G19 M13 L7 Q2 F15 S2 E15
  R2 ->     260 (V: 99.69%) (N:  0.43%) PV: R2 G19 M13 L7 Q2 F15 R4 E15 T4
  B4 ->     255 (V: 99.58%) (N:  0.55%) PV: B4 G19 M13 L7 B2 A14 Q2 F15
 S11 ->     219 (V: 99.66%) (N:  0.40%) PV: S11 G19 M13 F15 Q2 E15 pass G14
  L1 ->     147 (V: 99.53%) (N:  0.36%) PV: L1 K1 G19 L7 M13 F15 B2 E15 R4
  T4 ->     146 (V: 99.66%) (N:  0.27%) PV: T4 G19 M13 L7 S3 F15 R4 E15 Q2
 B11 ->     141 (V: 99.35%) (N:  0.45%) PV: B11 A12 G19 L7 M13 F15 Q2 E15 R4
 P19 ->     110 (V: 99.21%) (N:  0.39%) PV: P19 Q18 G19 L7 M13 F15 Q2 E15 S2
  T5 ->     107 (V: 99.62%) (N:  0.22%) PV: T5 G19 M13 L7 Q2 F15 S2 E15 T4
  P1 ->     100 (V: 99.63%) (N:  0.20%) PV: P1 G19 M13 L7 Q2 F15 S2 E15 R4
  T7 ->      92 (V: 99.65%) (N:  0.17%) PV: T7 G19 M13 L7 Q2 F15 S2
  Q1 ->      91 (V: 99.63%) (N:  0.18%) PV: Q1 G19 M13 L7 S10 F15 Q2 E15
  D1 ->      83 (V: 99.56%) (N:  0.19%) PV: D1 G19 M13 L7 Q2 F15 S2 E15
 O15 ->      79 (V: 99.53%) (N:  0.18%) PV: O15 G19 M13 L7 Q2 A14 pass F15
  T2 ->      74 (V: 99.61%) (N:  0.15%) PV: T2 G19 M13 L7 Q2 A14 S3 F15
 R11 ->      71 (V: 99.65%) (N:  0.13%) PV: R11 G19 M13 L7 Q2 F15 S2 E15 pass
  B1 ->      71 (V: 99.61%) (N:  0.15%) PV: B1 G19 M13 F15 R4 E15 Q2
  T1 ->      71 (V: 99.59%) (N:  0.15%) PV: T1 G19 M13 L7 Q2 F15 S3 E15 T4
  T3 ->      70 (V: 99.59%) (N:  0.15%) PV: T3 G19 M13 L7 Q2 F15 T4 E15
  R1 ->      69 (V: 99.63%) (N:  0.14%) PV: R1 G19 M13 L7 Q2 F15 S2 E15 pass
  T6 ->      69 (V: 99.62%) (N:  0.14%) PV: T6 G19 M13 L7 Q2 A14 pass F15
 Q18 ->      69 (V: 99.56%) (N:  0.16%) PV: Q18 P18 G19 L7 M13 F15 Q2 E15 S2
  S1 ->      66 (V: 99.55%) (N:  0.15%) PV: S1 G19 M13 F15 B2 E15 Q2 G14
 N12 ->      51 (V: 99.54%) (N:  0.12%) PV: N12 G19 M13 L7 B2 F15 Q2 E15
 A12 ->      50 (V: 99.44%) (N:  0.14%) PV: A12 B11 G19 F15 M13 E15 B2 G14 S10
  E1 ->      48 (V: 99.48%) (N:  0.12%) PV: E1 G19 M13 L7 Q2 F15 S2 E15
 G15 ->      45 (V: 98.86%) (N:  0.23%) PV: G15 G19 M13 F15 E15 L7 Q2 G14 S2
 C19 ->      41 (V: 99.40%) (N:  0.12%) PV: C19 B19 G19 F15 M13 E15 R4
 A15 ->      38 (V: 99.36%) (N:  0.12%) PV: A15 A14 G19 L7 M13 F15 B2 E15 Q2
 F15 ->      15 (V: 98.11%) (N:  0.14%) PV: F15 G19 M13 L7 R4 A14 Q2
73581 visits, 7060980 nodes, 73580 playouts, 1246 n/s
[text]
```

**Comment by killerducky** [comment] 2018-02-27 05:18
Ok I figured out a way to force which of the eight rotations to use for the heatmap. I picked the one that has Black's M13 as the lowest value (0.04%). So now after White plays G19, Black doesn't explore M13 at all even after 100,000 visits. See below it will explore O12 with a policy of 0.14% next. There are 45 total unexplored moves, and M13 is dead last. 

Well it's still not a bug, the Net needs to learn this better. BTW note that FPU reduction is hurting this case because it sacrifices width to gain depth in search.

```
  P1 ->   52017 (V: 15.76%) (N:  0.89%) PV: P1 L7 L6 K6 K7 Q18 P18 O2 N8 N11 M8 Q5 L3 G5 G4 M13 F15 B2 E15 Q2
  Q5 ->    7812 (V:  0.56%) (N:  7.77%) PV: Q5 M13 N8 N11 M8 L3 G4 G5 L7 Q2 F15 S2
  N8 ->    7533 (V:  0.34%) (N: 16.89%) PV: N8 N11 M8 Q5 L3 G5 G4 M13 L7 Q2 F15 S2 E15
  M8 ->    7506 (V:  0.39%) (N: 14.67%) PV: M8 N11 N8 Q5 L3 G5 G4 M13 L7 Q2 A14 S2
 F15 ->    4868 (V:  0.36%) (N: 10.47%) PV: F15 M13 E15 Q5 N8 N11 M8 L3 L7 G5 G4 Q2
  L7 ->    3538 (V:  0.45%) (N:  5.78%) PV: L7 M13 N8 N11 M8 Q5 L3 G5 G4 Q2 A14 S2
 N11 ->    2001 (V:  0.37%) (N:  4.14%) PV: N11 N12 M8 N11 N8 Q5 L3 G5 G4 M13 L7

  S1 ->      46 (V:  0.20%) (N:  0.14%) PV: S1 M13 R2 S3 P1 O2 Q2 S2
  J2 ->      41 (V:  0.00%) (N:  0.17%) PV: J2 L1 K1 L3 N8
 O12 ->       0 (V:  0.13%) (N:  0.14%) PV: O12
 R10 ->       0 (V:  0.13%) (N:  0.14%) PV: R10

 M13 ->       0 (V:  0.13%) (N:  0.04%) PV: M13
100000 visits, 9822446 nodes, 99999 playouts, 1131 n/s
```

**Comment by killerducky** [comment] 2018-02-27 05:24
Here is the same thing with `--fpu_reduction 0.0`. It finds M13 by 4035 playouts.

```
>>genmove b
Thinking at most 2678400.0 seconds...
NN eval=0.001317
Playouts: 1389, Win:  0.47%, PV: M8 N11 N8 Q5 L3 G5 G4
Playouts: 2903, Win:  9.35%, PV: M8 N11 N8 Q5 L3 M13 L7
Playouts: 4035, Win: 34.73%, PV: M13 L14 M14 N11 N8 M8 L7 Q5 L3
Playouts: 5288, Win: 50.15%, PV: M13 L14 M14 N11 N8 M8 L7 Q5 L3 G5
Playouts: 6590, Win: 59.96%, PV: M13 L14 M14 N11 N8 M8 L7 Q5 L3 G5
Playouts: 7897, Win: 66.55%, PV: M13 L14 M14 N11 N8 M8 L7 Q5 L3 G5 G4
Playouts: 9233, Win: 71.38%, PV: M13 L14 M14 N11 N8 M8 L7 Q5 L3 G5 G4

 M13 ->    7356 (V: 99.75%) (N:  0.04%) PV: M13 L14 M14 N11 N8 M8 L7 Q5 L3 G5 G4
  M8 ->     482 (V:  0.71%) (N: 14.67%) PV: M8 N11 N8 Q5 L3 M13 L7
  N8 ->     465 (V:  0.47%) (N: 16.89%) PV: N8 N11 M8 Q5 L3 M13 L7
 F15 ->     256 (V:  0.28%) (N: 10.47%) PV: F15 M13 E15 Q5 N8 N11
  Q5 ->     231 (V:  0.58%) (N:  7.77%) PV: Q5 M13 N8 N11 M8 L3 G4
```

**Comment by Splee99** [comment] 2018-02-27 05:35
Thanks. How did you enter the option for fpu reduction? I copied from your log and it didn't work here.

**Comment by killerducky** [comment] 2018-02-27 05:48
In config.h comment this: `#define USE_TUNER`

Also you can force the heatmap by going to the position, and running `heatmap N` where N is [0,7]. This will replace the NNCache entry with the heatmap rotation you specify. Then when you start the analysis it will use that heatmap rotation. You can run multiple heatmap commands until you find the one you want to test.

**Comment by Splee99** [comment] 2018-02-27 05:53
Got it, Thanks.

**Comment by wctgit** [comment] 2018-02-27 11:13
Great detective work, guys. 👍 :-)

**Comment by sethtroisi** [comment] 2019-02-14 06:03
closing, no active discussion for ~1 year with subsequent issues and PRs

**Closed by sethtroisi** 2019-02-14 06:03 UTC
