### ISSUE TITLE
[Question] Thinking at most N seconds.

### ISSUE THREAD

**Issue by jslechasseur** [leela-zero/leela-zero#1085] opened 2018-03-23 15:41 UTC
I understand how to limit the visits or the playouts. When I don't, leelaz still thinks for at most 50.0 secs, independently of the hardware I use.

Is there a way to allow for more thinking time? 

Even better, is there a way to ask leelaz to look at a position for at least K visits (or nodes, or playouts)?

**Comment by hydrogenpi** [comment] 2018-03-23 15:53
I'm wondering why no promotions of new networks for so long, but can confirm that when setting LZ to use long time settings that it is way stronger than AQ by leaps and bounds. In fact for analysis games or non-realtime games like correspondence games, LZ is already pretty much a top level pro even with current 10 block.

**Comment by gcp** [comment] 2018-03-23 16:00
Note that right now it will still stop if reaches the memory limit, which is about 280k nodes in 64-bit mode.

An improvement for this was merged in "next" this morning.

**Comment by jslechasseur** [comment] 2018-03-23 16:04
I finally found the syntax. I share it here for others like me who are not familiar with GTP :

time_settings: Set time allowance
Arguments: int main_time, int byo_yomi_time, int byo_yomi_stones
Fails:     syntax error
Returns:   nothing

For example, one can set 

time_settings 0 100 1

to make sure Leelaz will think at most 100 secs per move. Sabaki makes this easy with the initial command option:
![image](https://user-images.githubusercontent.com/35378510/37839964-3a595404-2e92-11e8-8692-02e288bcfb1b.png)

**Comment by roy7** [comment] 2018-03-23 16:16
Perhaps someone could add that info, or a link to your post, into the README or FAQ.

**Comment by hydrogenpi** [comment] 2018-03-23 16:18
You can also specify a -p constraint for playouts. 
https://www.lifein19x19.com/viewtopic.php?f=18&t=15511

**Comment by jslechasseur** [comment] 2018-03-23 16:26
Thanks @gcp, I didn't think about disabling time management.

**Comment by FFLaguna** [comment] 2018-03-25 10:29
Note that LZ also acts properly if you change "time_settings" in the middle of a game, EXCEPT if you do so while it is pondering during the opponents turn. In that case, it will stop pondering until you play the opponent's next move.

But other than that, changing "time_settings" on the fly works as intended in every other way.

**Comment by d7urban** [comment] 2018-03-29 08:24
Note: the gtp command to set infinite thinking time is `time_settings 0 1 0` 
I know I had a hard time finding this, perhaps others have too.

(Any "time_settings a b c" where b>0 and c=0 works)

**Comment by emesterhazy** [comment] 2018-04-01 14:44
I'm using `time_settings 0 10 1` to limit Leela's thinking time, but it ends up thinking much longer (possibly forever). The GTP console says "Thinking at most 9.0 seconds....", but it seems like there is an issue since Leela never plays a stone.

Any ideas? I'm also using `--playouts 100 --noponder` to limit the number of playouts, but it hasn't seemed to help.

Version Info
---
OS: MacOS 10.13.3
Sabaki: v0.33.3
Leela: v0.11.0

**Comment by iteachcs** [comment] 2018-04-01 18:16
> I'm using time_settings 0 10 1 to limit Leela's thinking time, but it ends up thinking much longer (possibly forever). The GTP console says "Thinking at most 9.0 seconds....", but it seems like there is an issue since Leela never plays a stone.

Any ideas? I'm also using --playouts 100 --noponder to limit the number of playouts, but it hasn't seemed to help.

10 10 1 has been working for me.

**Comment by chucklu** [comment] 2018-09-25 13:01
@earthengine  Do you know  how to modify the playouts during the game?
Just like the `time_settings` command

**Comment by sethtroisi** [comment] 2019-02-14 06:13
closing, no active discussion with solutions proposed

**Closed by sethtroisi** 2019-02-14 06:13 UTC
