### ISSUE TITLE
help:when and where to see second game of leelaz vs Haylee ?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1346] opened 2018-05-05 21:35 UTC
thanks

**Comment by hydrogenpi** [comment] 2018-05-05 21:39
ogs , 11am cst

**Comment by hydrogenpi** [comment] 2018-05-05 21:39
i will be live streaming twitch, two lizzie side by side, one is lz one is lzelf

**Comment by hydrogenpi** [comment] 2018-05-05 21:40
hopefully roy will use 8xV100 with LZELF in the match against haylee but realistically he will do only sinhle gtx1080ti

**Comment by roy7** [comment] 2018-05-05 21:41
The plan us to use a 4xV100 AWS machine that I think you donated to pay for.

**Comment by hydrogenpi** [comment] 2018-05-05 21:56
Oh I didn't know that. Anyway since your running the bot I felt you seemed pretty admanant on single gtx1080Ti but if you do indeed decide to test it out with the v100 instance hopefully you precheck to make sure its working in the linux (I recently had issues getting gtp2ogs to install with node on server 2016 in aws instance) and performance are up to par (I noticed on very rare occasions a GPU might detach or not attach correctly right after boot since on aws its all virtual stuff) and ready to go with net 131.

**Comment by jkiliani** [comment] 2018-05-05 21:59
Are we using the ELF net or just a regular 15 block one? As excited as everyone is about ELF, I think the consensus even before anyone heard of Facebook's efforts was that Leela Zero had at least top professional strength already when using good hardware. I'd keep on using our regular nets, especially since ELF won't be able to give handicap the week after, while our normal nets may be able to handle H2.

**Comment by l1t1** [comment] 2018-05-05 22:14
thanks

**Comment by l1t1** [comment] 2018-05-05 23:43
i saw this game by chance, is that same fineart some days ago play with leelaz https://online-go.com/game/12749878?

**Comment by roy7** [comment] 2018-05-05 23:45
That account has nothing to do with the FineArt GO AI, it's just a user who chose that name.

Next Haylee game is tomorrow morning at noon eastern USA time. 16 hours from now.

**Comment by hydrogenpi** [comment] 2018-05-05 23:54
@l1t1 lol that account is a cheater, I reported him here: https://forums.online-go.com/t/leela-zero-progress-thread/16169/60?u=thebeginer

THis is why the roy bots get low rankings, people with DDK using AI bots to score wins.

**Comment by Mardak** [comment] 2018-05-06 09:17
It sounds like for the match with Haylee, the desire is to have strong play from the latest network with good hardware. Has anyone looked into turning on `-n` noise as it disables `fpu_reduction` and could leverage all the additional / "excess" visits to avoid blunders or discover something amazing?

@roy7 estimates about 4000 nodes/sec for the upcoming game, so giving all 19x19 possible moves a sanity check is less than 0.1 seconds worth of pondering.

**Comment by Mardak** [comment] 2018-05-06 15:52
For some more details on why I bring up turning on noise, here's a "snapback" #877 game
https://online-go.com/game/11952774

Using the same network from the game 5b90bd32, here's the move visited move of analyzing each symmetry with 4530 visits:
```
expect: T7, move: 129, who: b, weight: 5b90bd32, visit: 4530
symmetry: 0 T7 ->    4430 (V: 99.97%) (N:  3.08%) PV: T7 B10 C10 B9 G13 F12 H14 H15 G15 F14 G16 F17 G17
symmetry: 1 T7 ->    3983 (V: 99.97%) (N:  1.38%) PV: T7 B10 C10 B9 G13 F12 H14 H15 F14 G15 F13 E12 F15
symmetry: 2 T7 ->    4496 (V: 99.96%) (N: 16.66%) PV: T7 B10 C10 B9 G13 F12 F11 G12 H12 G11 H11 F10 E11 F9 H8
symmetry: 3 T7 ->    4499 (V: 99.96%) (N:  9.05%) PV: T7 B10 C10 C9 B11 R12 S12 Q12 S14 M18 L17 L18 K16 J16
symmetry: 4 B9 ->    1645 (V:  0.64%) (N: 34.31%) PV: B9 B8 C9 D9 D10 E9 E7 D7 E8 D8 B4 B5 A3 A5 E5 E6 F6
symmetry: 5 B9 ->    1853 (V:  0.39%) (N: 34.68%) PV: B9 B8 C9 D9 E7 D7 E8 D8 B4 B5 A3 R2 B6 A5 B7 A7
symmetry: 6 T7 ->    4495 (V: 99.94%) (N: 13.16%) PV: T7 B10 C10 B9 G13 R12 S12 Q12 S14 B16 H14
symmetry: 7 T7 ->    4497 (V: 99.91%) (N: 12.34%) PV: T7 B10 C10 B9 D15 E15 E16 B16 E17 D18 E18 D17 H17 J18 H18 G16
```

And the same thing but with `-n` to turn on noise (and to turn off fpu_reduction) and with 1/10 the visits:
```
expect: T7, move: 129, who: b, weight: 5b90bd32, visit: 453
symmetry: 0 T7 ->     436 (V: 99.99%) (N:  2.57%) PV: T7 B10 C10 B9 G13 F12 H14 H15 G15
symmetry: 1 T7 ->     403 (V: 99.98%) (N:  1.14%) PV: T7 B10 C10 B9 G13 F12 H14 H15 F14 G15
symmetry: 2 T7 ->     446 (V: 99.99%) (N: 12.64%) PV: T7 B10 C10 B9 G13 F12 F11 G12 H12
symmetry: 3 T7 ->     447 (V: 99.99%) (N:  6.83%) PV: T7 B10 C10 C9 B11 R12 S12 Q12 S14 M18 L17 L18
symmetry: 4 T7 ->     123 (V: 100.00%) (N:  0.23%) PV: T7 B10 C10 B9 G13 F12 H14 H15 F14 G15
symmetry: 5 T7 ->     289 (V: 99.99%) (N:  0.40%) PV: T7 B10 C10 B9 G13 F12 F11 G12 H12
symmetry: 6 T7 ->     447 (V: 99.98%) (N:  9.93%) PV: T7 B10 C10 B9 G13 E12 E11 F11 E10
symmetry: 7 T7 ->     447 (V: 99.97%) (N:  9.37%) PV: T7 B10 C10 B9 D15 E15 E16 B16 E17 D18 E18
```

This generally seems to work for all the "one bad rotation" failures as the correct move just had such low prior for a given symmetry that it isn't even searched when given a lot of visits.

**Comment by roy7** [comment] 2018-05-06 16:15
Game #2 is live. https://online-go.com/game/12760703

**Comment by hydrogenpi** [comment] 2018-05-06 16:55
Looking forward to handicaps now! :)

**Comment by Friday9i** [comment] 2018-05-06 18:39
Yes, I guess with strong hardware, 1 stone penalty (ie 2 stones for Black, komi for white) will not be enough. Will the 2 Black stones be on hoshi or freely placed by Haylee?

**Comment by WYVYW** [comment] 2018-05-06 18:42
https://www.youtube.com/watch?v=vBwvMSN7h10

**Comment by Splee99** [comment] 2018-05-06 19:34
It appears to me that with stronger hardware than that used the 1st game, the bot becomes more aggressive, for good reasons.

**Comment by marcocalignano** [comment] 2018-05-06 21:04
I am disappointed! Leela zero could win with a GTX 1080   and would be a more impressive result. I do not regard this result as really good since I will never be able to reproduce it on my own computer. Winning with a GTX 1080 would be much more impressive. Plus for me is not fear to Haylee to improve the network and the hardware after she lost the first game.

**Comment by WYVYW** [comment] 2018-05-06 21:27
To beat a pro with a low end hardware - build-in-graphics-card (or smartphone) is an achievement which has not been done before and would call for more attention.

**Comment by hydrogenpi** [comment] 2018-05-06 21:29
Once the handicaps start stacking up, even 8xV100 might not be enough. The original point of this series is for high handicaps not playing on even.

**Comment by jkiliani** [comment] 2018-05-06 21:31
I'm also a bit ambiguous about going very high on the hardware. While this may in theory lead to impressive play, we should consider being good sports and giving her a fair chance on H2, by using just a GTX 1080 or even 1060...

**Comment by hydrogenpi** [comment] 2018-05-06 21:35
imho the V100 isn't as powerful as people think, its marginally better than a titanV and that itself is not that much better than a 1080Ti. By the 7th and 8th week if all goes well Haylee will get three handicap stones, there is zero chance that LZ can win on a single gtx 1080 or 1060... just not remotely possible.

**Comment by jkiliani** [comment] 2018-05-06 21:39
I don't see it as a failure to lose at H3 against a professional player. So what if she wins some of the later games? If we arrange all matches against professionals in a way that makes it almost certain that LZ wins, we may run out of pros willing to participate in such matches. Haylee was nice enough to agree to this match series and promote Leela Zero by doing so, we don't have to go out of our way to demotivate her...

**Comment by hydrogenpi** [comment] 2018-05-06 21:44
Okay I see your point, she did seem sort of demotivated and didn't even finish the game this time. But just one thing to note, going all out would have been using 8xV100 (highest publically available at the moment). Since her first game we only gotten two net networks (I'm not complaining but just saying its nothing like the three networks a day we got during the golden age) and everyone knows LZ is terrible at high handicaps so if you are suggesting using average hardware at H3 or H2, I think that very quickly flips the tables completely around. But anyway its up to Haylee/Roy what happens, fwiw she did mention in todays video she didn't mind if better hardware/ newer networks were used because her goal was to find "just how strong LZ really is" and not to "beat LZ".. Based on the rules, if LZ loses game 3, the most we will see from this series is 2H. I'm okay with that personally but just wanted to note the original point of the series is to see how many handi LZ can give Haylee at its best

**Comment by l1t1** [comment] 2018-05-06 21:55
thanks, I wish both sides can discuss and agree with how to change  the following games to make them more balance

**Comment by Tsun-hung** [comment] 2018-05-07 01:12
> I am disappointed! Leela zero could win with a GTX 1080 and would be a more impressive result. I do not regard this result as really good since I will never be able to reproduce it on my own computer. Winning with a GTX 1080 would be much more impressive.

I have said that the hardware of 1060 is enough to win Haylee(see #1261), but many didn't notice. Actually, the latest 10B network is a match for Pro.

**Comment by gcp** [comment] 2018-05-07 08:00
>The plan us to use a 4xV100 AWS machine that I think you donated to pay for.
>Anyway since your running the bot I felt you seemed pretty admanant on single gtx1080Ti
>But I think unlike many Pros, Haylee is a very good sport and won't mind that "turn up the heat" so to speak.

The choice to use the best hardware possible was a result of my phone call with Haylee which was discussed in the "pro game at 7 million" thread. Haylee seemed to think Leela has to prove herself against lower pro's first and this might get stronger pros interested. Clearly, at least Haylee was apparently not completely convinced about the strength we could bring to bear, which is perhaps also why she wanted to work her way up towards handicap.

So I urged @roy7 to use the hardware @hydrogenpi had already paid for (and which, by the way, anyone can rent...) and make sure it was a convincing victory. I haven't seen the video yet, but I gather Haylee got crushed.

Perhaps she has revised her opinion on LZ's strength now. But as we know, a handicap game might be much harder. Given that the pro match is out of the way and the pro strength thing effectively settled, I have no strong feelings about the hardware to use for the next games.

**Comment by hydrogenpi** [comment] 2018-05-07 16:53
So now we are back to the good old days of getting multiple new nets a day, any guesses as to how handicap ability will be affected for Sundays game a week from now? Will LZ get worse at handicap or will it not follow the fate of ELF since its being trained with the t=1 all the ways?

**Comment by Splee99** [comment] 2018-05-07 17:27
Hope the newly trained LZ doesn't behave like the current ELF weight, which tends to have ladder issues easily in handicap games.

**Comment by gcp** [comment] 2018-05-07 18:10
We sure hope that t=1 training makes for better handicap games.

**Comment by hydrogenpi** [comment] 2018-05-08 01:33
is there a reason fb didnt train it for high handicap

**Comment by gcp** [comment] 2018-05-08 07:11
They followed the AGZ paper. Which is what we were also doing, anyway.

**Comment by sethtroisi** [comment] 2019-02-14 06:42
closing older issues

**Closed by sethtroisi** 2019-02-14 06:42 UTC
