### ISSUE TITLE
It seems white has larger winrate

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1212] opened 2018-04-17 07:37 UTC
I got data from http://zero.sjeng.org/match-games/5ad5116a7776b65b51c84381 and http://zero.sjeng.org/match-games/5ad1da22a679501dfd1200f1,then created two tables in oracle.
and run following sql:
SQL> select substr(score,1,1)color,count(*)from match group by substr(score,1,1);

C   COUNT(*)
- ----------
W        254
B        190

SQL> select winner,substr(score,1,1)color,count(*)from match group by substr(score,1,1),winner
SQL> /

WINNER   C   COUNT(*)
-------- - ----------
f3231682 W        107
8a045bce B        114
f3231682 B         76
8a045bce W        147

SQL> select winner,substr(score,1,1)color,count(*)from match0 group by substr(score,1,1),winner
SQL> /

WINNER   C   COUNT(*)
-------- - ----------
f3231682 W        129
c0cb605b W        112
f3231682 B        107
c0cb605b B         86

SQL> select substr(score,1,1)color,count(*)from match0 group by substr(score,1,1);

C   COUNT(*)
- ----------
W        241
B        193

in 800+ games, **white beat black by about 5:4**, whether which one the winner is.

**Comment by alreadydone** [comment] 2018-04-17 07:49
55% winrate for white is pretty close to [AlphaGo](https://www.reddit.com/r/MachineLearning/comments/76xjb5/ama_we_are_david_silver_and_julian_schrittwieser/doljugm/), but seemingly in disagreement with [AlphaGo Teach](https://alphagoteach.deepmind.com/)...

**Comment by l1t1** [comment] 2018-04-17 08:14
if it is true, can you speed up PASS by dispatching more white to the challenger? @gcp

**Comment by gcp** [comment] 2018-04-17 12:34
>if it is true, can you speed up PASS by dispatching more white to the challenger? @gcp

I don't want PASS, I want **stronger networks**.

**Comment by l1t1** [comment] 2018-04-17 14:02
which one is bigger,     (1+1/n)^n,(1+1/m)^m ,when n<m?

**Comment by Alderi-Tokori** [comment] 2018-04-17 15:32
@l1t1 Depends on the values of n and m. Also I don't see what this has to do with anything.

**Comment by Eddh** [comment] 2018-04-17 15:52
The difference could also be explained by training artefacts. For example, the first move of the game is from black, and doesn't benefit from tree reuse. All white moves will benefit from tree reuse. That means black gets 1 move that is fully affected by dirichlet noise while white doesn't. Probably does not lead to a big difference especially since the first move shouldn't matter that much, but given temp=1 too, who knows..

**Comment by gcp** [comment] 2018-04-17 17:40
@Eddh that theory could be tested by comparing self-play with match data.

**Comment by l1t1** [comment] 2018-04-18 00:56
I suppose that a network has faster PASS 55%, the actual level was 52%, then in a peroid, 
if it produced 10 networks, the acutal level of 10th netwrok is about (104/96)^10=2.23, 
if standard PASS 55% produced  5 networks, the acutal level of 5th netwrok is about (110/90)^5=2.72, the standard PASS is better, but if it only   produced  2 networks, the 2nd is  about (110/90)^2=1.49. it is worse.
but i have no idea about the actual level and number of new networks through. @Alderi-Tokori

**Comment by marcocalignano** [comment] 2018-04-18 14:14
The difference in winning rate can also give by the Komi value. It seems that 7.5 Komi, (6.5 Japanese) Is too much for really good player. Park Junghwan and Ke Jie, the two best player in the world at the moment, when the play each other, the one that has white wins always.

**Comment by alreadydone** [comment] 2018-04-18 18:36
>  the one that has white wins always.
except for one (early) game.

**Comment by stephenmartindale** [comment] 2018-04-24 12:51
I've done some analysis of the available data and I have some results to report.

Firstly, however, I'd like to point out that the AlphaGo data available is useless when it comes to judging whether black or white is favoured: quite simply, we don't have enough of it and we don't know the selection criteria used to select the 50 games, 5 games, 55 games etc.. It certainly wasn't random!

Now, my conclusions:

- Leela Zero has an affinity for white.
- Match games display a stronger bias than self-play games. (Sorry, @Eddh. I, too, was hoping that this would not be the case because, if it was, I could propose some possible solutions such as playing a certain number of self-play games at 5.5 komi in order to "teach" LZ not to lean on the komi like a crutch.)

Here is a graph:

![2018-04-24 last 30 matches that resulted in promotion](https://user-images.githubusercontent.com/6370145/39186419-a2cf97fe-47ca-11e8-98e5-b62d560be297.png)

This graph shows the last nine matches between the incumbent promoted network and the network that would usurp them and claim the throne. At the time that each match was played, these two networks would, in theory, have been the strongest known weights. For each match, the graph shows the number of wins for black and white, respectively, as well as an indicator ("x") showing whether a test for bias rejected the null-hypothesis or not. Specifically, the null hypothesis was that black and white had equal chances of winning and the confidence level of the test was 0.01.

I chose this graph because it is the most understandable but the data taken in aggregate also supports this conclusion, as does data broken down by network instead of by match.

Next, because @gcp suggested it, I took a crack at the self play data:

![2018-04-24 self-play games](https://user-images.githubusercontent.com/6370145/39186795-db3ec0c8-47cb-11e8-937d-02d686cc03c1.png)

Note that this graph shows wins and losses by network and only includes the five most recent, promoted networks included in the `all.sgf.xz` file that I downloaded: 17-Apr-2018. These are the networks that would have played in the matches included in my match-game graph, above.

Here, too, there is evidence to reject the null hypothesis and to conclude that white is favoured.

HOWEVER... Over the nine matches covered in my graph, white won 57.63% of the 3998 match games. White won only 52.95% of the 141940 self-play games included in my sample. There is no evidence to suggest that self-play games are more strongly biased than match games and so I conclude that the bias is not, in fact, due to noise or a first-move advantage.

WHY the bias exists, how large it is, whether it is a training artefact or whether komi is "wrong" for Leela Zero or "wrong" for Go, universally, I haven't a clue. I think it is pretty clear that the bias does exist but I am not about to speculate on the cause. I also don't know what is to be done about it. Personally, I just wanted to take a look at the data because, as a Go player, I was intrigued by what I might find.

If you want to see the other angles from which I scrutinised the data or you want to repeat my experiments, here's my iPython notebook: https://github.com/stephenmartindale/zerozeug/blob/master/Match-Statistics.ipynb

**Comment by marcocalignano** [comment] 2018-04-24 15:00
A way to find out if it is indeed the komi, is to modify the komi value to 6.5 or 5.5 in the validation code. And then let one network play against itself for a big number of game and recalculate the graph above. 
In this way you eliminate the random moves from the self play and you can see if white wins even with less komi.

**Comment by stephenmartindale** [comment] 2018-04-24 15:42
@marcocalignano : Unfortunately, it is not so simple. If you use the current best network (the most logical choice) and had it play against itself with any komi other than 7.5, you would only be testing the magnitude of the mistakes it would make due to the komi being "wrong": it was trained with 7.5 and would have learned to value positions based on that.

To test, properly, you would have to train a new network on games played with a different komi value. Sure, you could start with the current best weights but you would need at least a few generations of networks before you could consider the result to be accurate.

I would argue that doing this for a few generations wouldn't really hurt Leela Zero in the long run. Adding three or four generations trained at 5.5 might even "immunise" LZ against the effects and ill-effects of komi and *improve* performance down the road -- you never really know, with deep learning. ;) (Crazy stuff works in *this* field: see Knockout!)

But why do that? The aim of the project seems to be to faithfully reproduce the AlphaGo Zero work, not to try to prove whether komi should be 7.5 or 5.5. It's interesting to note that Leela Zero thinks the komi favours white and it is interesting to debate the possible causes and consequences of this but that's where we should stop in my opinion.

**Comment by stephenmartindale** [comment] 2018-04-25 07:54
If that's the case, I stand corrected. I would assume that it works as you say but I do recall there being some issues, here, related to komi being ignored entirely.

**Comment by sethtroisi** [comment] 2019-02-14 06:19
closing, no active discussion for ~1year. winrate imbalanced leveled out

**Closed by sethtroisi** 2019-02-14 06:19 UTC
