### ISSUE TITLE
Any idea why I can't push my GPU to use more than 80% for Leela Zero?

### ISSUE THREAD

**Issue by SharlatanY** [leela-zero/leela-zero#295] opened 2017-12-08 07:53 UTC
My GPU usage looks as follows:

> 1 instance -> ~ 28% (8% CPU)
> 2 instances -> ~ 53% (15%  CPU)
> 3 instances -> ~ 75% (22% CPU)
> 4 instances -> ~ 80% (28% CPU)
> any more instances -> stays at 80% GPU usage but CPU usage continues to increase for about 7% for every new instance

It just doesn't seem to go over 80%. I don't think it's a CPU bottleneck since I've got an octacore (Ryzen 1700x) and Leela uses only one thread per instance now (and CPU usage is low anyway), so, more than 4 instances shouldn't be a problem. I also don't think that the card's thermal throttling or something like that. Temperature is at about 62°C and I also don't have any problems to get GPU usage to 100% with programs like Furmark. Could this be a RAM to VRAM bottleneck?
If anyone has any idea about the cause (and maybe even a possible fix), I'd be more than happy to contribute some more GPU power to the project!

Thanks!

**Comment by BHydden** [comment] 2017-12-08 08:02
So you're running 14 instances then? :-D

**Comment by marcocalignano** [comment] 2017-12-08 08:29
There is a limit in the leela code that does not allow it to use more that 75% of GPU

**Comment by BHydden** [comment] 2017-12-08 08:32
I assume that is per instance? Have you tried two instances of -g 4 as opposed to one instance of -g 8? (or substitute whatever relevant numbers)

**Comment by sethtroisi** [comment] 2017-12-08 08:41
@marcocalignano you might be thinking of the limit on GPU memory in training ([code](https://github.com/gcp/leela-zero/blob/master/training/tf/tfprocess.py#L47))

**Comment by SharlatanY** [comment] 2017-12-08 08:45
Oh, thanks, didn't know that! That clears things up.
Maybe I could/should make a feature request for an optional parameter to control this value? Most of the time, I don't need my GPU anyway... it is a bit strange though; on my computer at work, usage still goes up to about 93%

@BHydden I tried both and it doesn't seem to make a difference.

**Comment by SharlatanY** [comment] 2017-12-08 08:46
@sethtroisi Oh, just saw your post after sending my last one. So, there's no GPU usage limit? Any idea what could be causing usage to not go over 80%?

**Comment by sethtroisi** [comment] 2017-12-08 08:53
My best guess is a slower CPU, my i5 can't saturate my GTX 1080 Ti

**Comment by SharlatanY** [comment] 2017-12-08 08:57
Yeah, but it's strange. I mean, I've got an 8 core and one instance of Leela only uses one core. And while GPU usage gets stuck around 80%, (at which point CPU usage is at around 28%), I can start further instances of Leela and CPU usage continues to rise. That's why I feel like the CPU itself isn't the bottleneck.

**Comment by qysnn** [comment] 2017-12-08 09:00
Same here. When I use 4 instances per GPU I have 85% utilization. With 10 instances, it is still 85%. So I think there may be some physical limitations.

**Comment by BHydden** [comment] 2017-12-08 09:01
Can I assume that when you say it stays at 80% you mean 4 instances use 20% each and 8 instances use 10% each? And even pushing the CPU all the way up to, say, 90% the gpu still stays soft capped at 80%?

**Comment by marcocalignano** [comment] 2017-12-08 09:02
Could also be the -t 1 option. Before with -t 2 the CPU was able to use the GPU better now not anymore.

**Comment by SharlatanY** [comment] 2017-12-08 09:10
@BHydden Yes, your example exactly describes the behavior I have: 4 instances => Every instance uses 20%; 8 instances => every instance uses 10%

I even took it to the extreme and went up to 99% CPU usage (reached at 16 instances) and GPU usage was stuck at 80%

**Comment by BHydden** [comment] 2017-12-08 09:14
Bizarre. Sorry if this is a stupid question but have you tried updating / reinstalling your graphics driver?
Since the problem is only on specific computers I have to imagine it's something client side.

**Comment by NTT123** [comment] 2017-12-08 09:18
In my experiments with CuDNN, I observed that leelaz uses a lot of CPU (at least in case of multiple instances) because it computes the two-head network (after residual layers) using CPU instead of GPU. 

Therefore, for each playout, if you have a fast GPU, it still have to wait CPUs to complete computing two-head network before moving on to the next playout.

**Comment by SharlatanY** [comment] 2017-12-08 09:19
No worries, not a stupid question! :)
Yes, already tried installing the latest drivers. Even cleaned up with old drivers with DDU beforehand.

Since neither the CPU nor the GPU seem to be the bottleneck, my best guess was/is some kind of throughput bottleneck somewhere but well, it's just a guess..

**Comment by barrtgt** [comment] 2017-12-08 09:42
I am only able to run 2 games simultaneously with a RX 480, any more and it is unstable. My gpu usage displayed under afterburner will show 100% usage, and task manager will show only 11% on the left column of the performance tab. But if you go into the gpu column there are new options included with the new Win 10 update that show usage under specific parts of the gpu including video encoding, decoding etc. For ATI there is a chart for 3 different compute: COMPUTE_0, COMPUTE_1 and COMPUTE_2. With Leela Zero 0.8 the COMPUTE_2 usage is around 50% for me but can fluctuate up to 80%. With 3 games running it could easily exceed this limit which would explain the stability issue I have. Earlier versions of Leela Zero would run partially on COMPUTE_1 I believe. I suspect it had to do with having 2 threads earlier, but I can't say for sure. CPU usage on my 8 thread i7-7700K hovers around 20%.

**Comment by SharlatanY** [comment] 2017-12-08 10:24
> Since the problem is only on specific computers I have to imagine it's something client side.
Sorry, for got to answer to that. Still think it might be a bandwidth limitation of some kind. Although my computer at work goes above 80%, it only has a 940MX, which really isn't anything to write home about. I imagine you don't need a lot of throughput to max that out.

Meanwhile I've got an 1080Ti at home, which is an entirely different story and might be limited by some bus bottleneck where Leela can't push data to the GPU fast enough. But since I've got no idea about Leelas inner workings, that's just a wild guess.

**Comment by gcp** [comment] 2017-12-08 10:28
All of this is very related to how "GPU Usage %" is measured. Windows 10 claims my GPU is like 40% in use with 1 thread, but if you look at the details you can see the compute load is actually closer to 80%.

**Comment by SharlatanY** [comment] 2017-12-08 10:38
Since Windows 10 doesn't seem to be too reliable, I used MSI Afterburner to get my stats. Don't know if there's a more accurate tool out there and/or if it maybe doesn't show some stat that would be at 100% already and which's responsible for the shown limit of 80%

**Comment by zediir** [comment] 2017-12-08 10:42
Same with me. GPU-Z shows 80% usage on both of my GTX1080. When running mining software it shows 100% usage.

**Comment by Marcin1960** [comment] 2017-12-08 11:40
Where can I get list of available autogtp options and their exact meaning?

**Comment by gcp** [comment] 2017-12-08 11:48
Run autogtp with -h.

**Comment by gcp** [comment] 2017-12-08 11:56
Another thing that can limit GPU utilization is the relatively small work calls that we do. On Windows I've observed that it seems to be hard to issue more than like 4000 OpenCL calls per second. Not so much on Linux. Coincidentally, I have no problems seeing 100% utilization there.

**Comment by SebastienFaurite** [comment] 2017-12-08 12:59
Leelaz is clearly faster on Linux. No problem to get 100% GPU. (GTX 1070)
Perhaps it is linked to the problem they have on Blender and Win10 with the WDDM, or Windows Display Driver Model.
http://blog.thepixelary.com/post/167616662857/improving-performance-of-blenders-cycles

**Comment by sethtroisi** [comment] 2019-02-14 08:09
closing old techsupport issue, this is probably resolved as larger NN has helped saturate GPUs

**Closed by sethtroisi** 2019-02-14 08:09 UTC
Labels: techsupport
