### ISSUE TITLE
[Question] Comparing best network to indirect ancestors

### ISSUE THREAD

**Issue by ThomasCabaret** [leela-zero/leela-zero#1123] opened 2018-03-30 08:45 UTC
Hi, I am wondering about how we asses the Bayes ELO of best networks? is it only an increment computed from the single match with the previous best network? how confident are we with the fact that the statistical winrate gap is transitive? if A beats B and B beats C can we consistently predict the outcome of an A-C encounter in our case? I am asking this because it seems to me quite possible to have some kind of playing style effects, next winner generation of a network can be good on the weaknesses of the previous one but develop unpunished weaknesses of itself, in some extent a rock-paper-scissor effect. **This kind of behavior could especially happens if the network size reaches its computational limits** _(where it will need to lose on some aspects to win on others)_. So how are we confident on the ELO estimation, and the transitivity of it, on an historical window of best networks, let's say the last 20 best ? Does the ELO gap we have computed predicts well the statistical outcome of encounters between networks that are not historical neighbors?
What do you guys think about it?

**Comment by Friday9i** [comment] 2018-03-30 09:24
Testing against a pool of old network would clarify the point, but if we go to "always select" approach rather than the 55% win rate threshold, putting in place a pool would be a waste of time.

**Comment by Hersmunch** [comment] 2018-03-30 09:26
Also see #349

**Comment by ThomasCabaret** [comment] 2018-03-30 09:41
Thx, what do we now of the genealogy of networks? is there a way to know from which network another has been made up?

**Comment by OmnipotentEntity** [comment] 2018-03-30 16:25
Also see https://github.com/gcp/leela-zero/issues/1054

**Comment by hydrogenpi** [comment] 2018-03-30 20:28
Good point OP, I compared the "ed" network of a while back that won against Haylee to the most recent 10 block and based on at least 55%, I did a 1.05^N where N is the number of new networks since the Haylee match and when using 1 playout (raw network) I was suprised that in a quick 100 game test, the new network is no where near as strong as its supposed to be?!?!?!

**Comment by hydrogenpi** [comment] 2018-03-30 23:42
Thanks for the formula @TFiFiE so in theory we should be  getting 

0.832766961
--

Which means the current best network should be one stone stronger than the one that played haylee?

**Comment by Eddh** [comment] 2018-03-31 09:39
If you use the raw network it's only using the policy and not the value head so it's hard to draw conclusion from that.

**Comment by gcp** [comment] 2018-04-03 09:42
> I am asking this because it seems to me quite possible to have some kind of playing style effects, next winner generation of a network can be good on the weaknesses of the previous one but develop unpunished weaknesses of itself, in some extent a rock-paper-scissor effect. This kind of behavior could especially happens if the network size reaches its computational limits 

This could happen but obviously from the AGZ/AZ results it was no observed. It's hard to have unpunished weaknesses when the self-play matches do a lot of exploration to find holes (especially after the FPU fixes).

**Comment by afalturki** [comment] 2018-04-03 10:54
@gcp What about running matches between different best networks not to check for regression but to get a more accurate elo difference as we know that the self elo scale is inflated.

**Comment by Friday9i** [comment] 2018-04-03 13:04
@afalturki It probably doesn't change things a lot in terms of inflated ELO.
Hypothesis: selfplay-scale is inflated as successive networks have a strong "proximity" (the NN are very close and the tree-exploration is the same: that makes a very strong proximity between successive networks).
Why does this proximity inflates selfplay ELO scale?
1) As new networks are close from their ancestors, they must share most of the weaknesses of their ancestors (obviously not all weaknesses, as they are stronger!)
2) Theses weaknesses are not a big deal for selfplay matches, as ancestors have the same weaknesses. Hence, new networks can perform well against ancestors (ie significant ELO jump for each generation) while still being weak on several aspects of the game.
3) On the other side, playing against other players / other bots, some of these weaknesses (eg ladders) will have a strong impact on the performance, putting a kind of ceiling to the maximal ELO reached: that is limiting the ELO gain, which cannot be as large as in selfplay!
Summary in a few words: the proximity of successive networks allows big ELO gains on selfplay, but Elo gains should be much more limited while playing various opponents (not sharing this proximity).
Not sure we can make a "proper mathematical proof" of that, but it seems logic and well proved by experience (AG, AZ, LZ: they all show that result. And Leela Chess also apparently).

**Comment by sethtroisi** [comment] 2019-02-14 06:14
closing, no active discussion for ~1year and much discussion elsewhere

**Closed by sethtroisi** 2019-02-14 06:14 UTC
